# 1_import_Busch2024_to_SMDAMAGE.py — Written by JFR and CoPilot (mostly Claude), 2026-07-01.
# Purpose: the completed database Busch2024_to_SMDAMAGE.sqlite is the data bridge between the Busch 2024 paper and SMDAMAGE.
# Later in the workflow, SMDAMAGE project file create_database.py reads Busch2024_to_SMDAMAGE.sqlite 
# and loads forestry bidders, one per (rotation_year, cluster_index), into the SMDAMAGE auction.
# Each bidder offers a carbon removal schedule and a bid-step supply curve to the auction.

# This is fiddly code, hard to get done in one pass. I pressed Copilot to improve the speed and avoid memory errors.
# It will take several hours.

# Origin: adapted from "1. Model loop all data corrected.do", the Stata pipeline published by Busch et al
# in "Cost-effectiveness of natural forest regeneration and plantations for # climate mitigation" (2024). 
# That Stata script reads per-country .dta input files, applies biome and geographic filters, 
# computes Chapman-Richards carbon growth curves under natural regeneration and plantation scenarios, 
# applies IPCC root-to-shoot ratios and FAO ecozone rules, evaluates cost-effectiveness per pixel in $/tCO2, 
# and selects the least-cost reforestation option for each pixel. The Stata code was the methodological source of truth.
# This Python translation reproduces that logic and extends it for use in SMDAMAGE.  Instead of writing MACC curves and map outputs, 
# it exports pixel-level parameters and year-by-year carbon sequestration schedules to a SQLite database. 
 
# With CoPilot, I converted "1. Model loop all data corrected.do" to Python and heavily modified it with additions for NPV costing, 
# rotation bucketing, and the full Busch-to-SMDAMAGE pipeline.

# Input to 1_import_Busch2024_to_SMDAMAGE.py:
#   (1) Input/*.dta published by Busch et al as the replication dataset for the 2024 paper. 
#    Not generated by any script in this repo; download from the paper's data repository. 
#     Each .dta file contains pixel information on one country. One row per pixel with
#     Chapman-Richards growth parameters (A, k) for natural regeneration and each plantation
#     genus, establishment costs, crop opportunity value, area, biome, FAO ecozone, and
#     geographic screen variables (griscom, brancalion, bastin, walker).
#   (2) Output/choose_harvest_years_mapping.csv, produced by 0_choose_harvest_years.py (Step 1 of the pipeline).
#   Maps every candidate rotation year to its chosen bucket representative; must exist before this script is run.

# Output from 1_import_Busch2024_to_SMDAMAGE.py: Output/Databases/Busch2024_to_SMDAMAGE.sqlite, two tables:
#   Undiscounted_dta_output, one row per pixel: country, pixel_id, plantation_genus,
#     selected_option (plantation/natural_regeneration), selected_A, selected_k,
#     selected_rotation_year, area_ha, crop_va_USD_per_ha_per_year,
#     selected_establishment_cost_USD_per_ha, p_USD_per_tC_harvested.
#   tC_per_h_per_year, one row per pixel per year (year 1 … selected_rotation_year):
#     country, pixel_id, year, tC_per_ha_per_year.
#
# Current per-pixel export pipeline for the Busch 2024 reforestation model:
# - Reads per-country .dta files via pd.read_stata, applies biome filtering, IPCC root-shoot ratios, continent/ecozonal rules, cost conversions,
# and plantation genus selection, then computes annual undiscounted carbon sequestration for each pixel under natural regeneration and plantation options.
# - Selects the cost-effective option per pixel and writes results to an sqlite file:
# one row per pixel in Undiscounted_dta_output and one row per pixel-year in tC_per_h_per_year.
#
# Harvest year bucketing: to keep the SMDAMAGE auction tractable, I wrote the code to map optimal rotation years 
# from the Faustmann rule to a smaller set of representative years. But this doesn't work very well.
# The code loads the mapping at runtime from HARVEST_YEAR_BUCKETS_CSV (Output/choose_harvest_years_mapping.csv), produced by 0_choose_harvest_years.py.
# You can change its CONFIG (k, maximum_harvest_year, discount_rate), then re-run this script to pick up the new buckets automatically.
# load_harvest_year_buckets() reads the CSV into a dictionary of original_harvest_year → chosen_harvest_year. 
# Then calculate_harvest_year() for each pixel's series. The resulting harvest years do not match the chosen set very well.
# Any year below the CSV minimum is set to the smallest chosen representative via a floor-fill in load_harvest_year_buckets(), 
# so all pixels enter the carbon loops with a valid bucket year and no raw sub-floor year leaks into the database.

# The remaining tables in Busch2024_to_SMDAMAGE.sqlite are added by later scripts in the pipeline:
#   2_k_means_carbon_removal.py — clusters pixels within each rotation year on their carbon
#     profiles; writes cluster centre schedules (carbon_removal_schedules) and assigns each
#     pixel a cluster_index (added as a column on Undiscounted_dta_output).
#   3_import_k_means_csv_to_sqlite.py — loads the k-means CSV results into the database.
#   4_move_Busch_data_to_SMDAMAGE.py — computes per-pixel NPV bid costs at four discount
#     rates and builds area-share bid-step curves (forestry_bid_curves), one curve per
#     (rotation_year, cluster_index, discount_rate) triple.

from __future__ import annotations
import argparse
import functools
import time
from pathlib import Path
import sqlite3
import numpy as np
import pandas as pd

SMDAMAGE_DB_FILE = "Busch2024_to_SMDAMAGE.sqlite"
SMDAMAGE_PIXEL_TABLE = "Undiscounted_dta_output"
SMDAMAGE_YEAR_TABLE = "tC_per_h_per_year"
TARGET_PIXEL_ID = 5119
RUN_ALL_PIXELS = True
GENUS_ORDER = ["pinu", "cunn", "euca", "brde", "brev", "nede", "neev"]
GENUS_BY_TYPE = {1: "neev", 2: "brev", 3: "brde", 4: "neev", 5: "cunn", 6: "euca", 7: "nede", 8: "neev", 9: "pinu", 10: "brde", 11: "neev", 12: "brde", 13: "brev", 14: "brde", 15: "neev"}
TIME_HORIZON_YEARS = 120  # Increased from 35: must cover the full rotation range (maximum_harvest_year=120 in 0_choose_harvest_years.py).
                          # Carbon schedules and establishment costs are computed over this horizon for all rotation lengths.
DISCOUNT_RATE = 0.03      # Changed from 0.05 to match 0_choose_harvest_years.py CONFIG.
                          # Used only for the Faustmann harvest-year rule in calculate_harvest_year();
                          # must match the discount_rate used to generate choose_harvest_years_mapping.csv.
AUSTMANN_F = 1
NATURAL_SOIL_C = 0.415107735
PLANTATION_SOIL_C = 0.092749069
AGB_C_POOL = 1
BGB_C_POOL = 1
SOIL_C_POOL = 1
HARVEST_C_POOL = 1
SMALL_DTA_COUNT = 50
SKIP_SQLITE_EXPORT = False
HARVEST_YEAR_BUCKETS_CSV = Path(__file__).resolve().parent.parent / "Output" / "choose_harvest_years_mapping.csv"
RESUME_AFTER_ISO = "KAZ"

AFRI = {"DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "COG", "CIV", "COD", "DJI", "EGY", "GNQ",
	"ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "LBY", "MDG", "MWI", "MDV", "MLI", "MRT", "MUS",
	"MAR", "MOZ", "NAM", "NER", "NGA", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TZA", "TGO", "TUN", "UGA",
	"ESH", "ZMB", "ZWE"}
AMER = {"ATG", "ARG", "BRB", "BLZ", "BOL", "BRA", "CHL", "COL", "CRI", "CUB", "DMA", "DOM", "ECU", "SLV", "GUF", "GRD", "GTM",
	"GUY", "HTI", "HND", "JAM", "MEX", "NIC", "PAN", "PRY", "PER", "KNA", "LCA", "VCT", "SUR", "TTO", "URY", "VEN"}
ASIA = {"AFG", "BGD", "BTN", "KHM", "CHN", "COK", "PRK", "FJI", "IND", "IDN", "IRN", "IRQ", "JOR", "KAZ", "KIR", "KGZ", "LAO",
	"LBN", "MYS", "MHL", "FSM", "MNG", "MMR", "NRU", "NPL", "OMN", "PAK", "PLW", "PSE", "PNG", "PHL", "WSM", "SLB", "LKA", "SYR",
	"TJK", "THA", "TLS", "TKL", "TON", "TKM", "TUV", "UZB", "VUT", "VNM", "YEM", "ARM", "AZE", "GEO", "TUR"}

NR_ROOTSHOOT_RULES = {(11, "AFRI"): 0.825, (11, "AMER"): 0.221, (11, "ASIA"): 0.207, (12, "AFRI"): 0.232, (12, "AMER"): 0.2845, (12, "ASIA"): 0.323,
	(13, "AFRI"): 0.332, (13, "AMER"): 0.334, (13, "ASIA"): 0.440, (16, "AMER"): 0.348, (16, "ASIA"): 0.322, (21, "AFRI"): 0.232, (21, "AMER"): 0.175,
	(21, "ASIA"): 0.230, (22, "AMER"): 0.336, (22, "ASIA"): 0.440, (23, "AMER"): 1.338, (23, "ASIA"): 1.338}
PL_ROOTSHOOT_RULES = {(11, "AMER"): 0.170, (11, "ASIA"): 0.325, (16, "AMER"): 2.158, (23, "ASIA"): 2.158}

WOOD_PRODUCT_STORAGE_MAP = {0.188: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "MEX", "NIC", "PAN", "SLV", "TTO", "VCT"},
	0.268: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PER", "PRY", "SUR", "URY", "VEN"},
	0.355: {"AFG", "ARM", "AZE", "BGD", "BTN", "CHN", "GEO", "IDN", "IND", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "KHM", "LAO", "LBN", "LKA", "MMR", "MNG", "MYS", "NPL", "OMN", "PAK", "PHL", "PNG", "PRK", "PSE", "SYR", "THA", "TJK", "TKM", "TLS", "TUR", "UZB", "VNM", "YEM"},
	0.392: {"AGO", "BDI", "BEN", "BFA", "BWA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "DZA", "EGY", "ERI", "ESH", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "LBY", "LSO", "MAR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NAM", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SWZ", "SYC", "TCD", "TGO", "TUN", "TZA", "UGA", "ZAF", "ZMB", "ZWE"},
	0.415: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}}
WOOD_PRODUCT_REVENUE_MAP = {52.65: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "NIC", "PAN", "SLV", "TTO", "VCT"},
	59.73: {"MEX"}, 61.04: {"BOL", "BRA", "COL", "ECU", "GUF", "GUY", "PER", "SUR", "VEN"}, 67.76: {"BGD", "IDN", "KHM", "LAO", "LKA", "MMR", "MYS", "OMN", "PHL", "PNG", "THA", "TLS", "VNM", "YEM"},
	69.26: {"PRY"}, 71.24: {"AGO", "BDI", "BEN", "BFA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "ERI", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SYC", "TCD", "TGO", "TZA", "UGA", "ZMB", "ZWE"},
	76.08: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}, 76.88: {"IND"}, 80.003: {"ARG", "CHL", "URY"}, 80.83: {"BWA", "NAM"},
	88.84: {"AFG", "ARM", "AZE", "BTN", "CHN", "GEO", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "MNG", "NPL", "PAK", "PRK", "PSE", "SYR", "TJK", "TKM", "TUR", "UZB"},
	93.40: {"DZA", "EGY", "ESH", "LBY", "LSO", "MAR", "SWZ", "TUN", "ZAF"}}
EXOTIC_SHARE_MAP = {0.74: {"AGO", "BWA", "COM", "DJI", "ERI", "SWZ", "ETH", "KEN", "LSO", "MDG", "MWI", "MDV", "MUS", "MOZ", "NAM", "SYC", "SOM", "ZAF", "SSD", "SDN", "TZA", "UGA", "ZMB", "ZWE", "BEN", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COG", "CIV", "COD", "GNQ", "GAB", "GMB", "GHA", "GIN", "GNB", "LBR", "MLI", "MRT", "NER", "NGA", "RWA", "STP", "SEN", "SLE", "TGO"},
	0.50: {"DZA", "EGY", "LBY", "MAR", "TUN", "ESH"}, 0.31: {"CHN", "PRK", "MNG"}, 0.40: {"BGD", "BTN", "KHM", "IND", "IDN", "LAO", "MYS", "MMR", "NPL", "PAK", "PHL", "LKA", "THA", "TLS", "VNM"},
	0.05: {"AFG", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "OMN", "PSE", "SYR", "TJK", "TKM", "UZB", "YEM", "ARM", "AZE", "GEO", "TUR"},
	0.78: {"COK", "FJI", "KIR", "MHL", "FSM", "NRU", "PLW", "PNG", "WSM", "SLB", "TKL", "TON", "TUV", "VUT"}, 0.32: {"ATG", "BRB", "CUB", "DMA", "DOM", "GRD", "HTI", "KNA", "LCA", "VCT", "TTO"},
	0.18: {"BLZ", "CRI", "SLV", "GTM", "HND", "JAM", "MEX", "NIC", "PAN"}, 0.97: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"}}

def get_continent(iso: str) -> str:
	return "AFRI" if iso in AFRI else "AMER" if iso in AMER else "ASIA" if iso in ASIA else ""

def mapped_value(mapping: dict[float, set[str]], iso: str, default: float = 0.0) -> float:
	return next((value for value, isos in mapping.items() if iso in isos), default)

def iter_input_isos(dta_dir: Path) -> list[str]:
	return sorted(path.stem.upper() for path in dta_dir.glob("*.dta") if path.is_file())

def iter_smallest_input_isos(dta_dir: Path, count: int) -> list[str]:
	paths = sorted((path for path in dta_dir.glob("*.dta") if path.is_file()), key=lambda path: (path.stat().st_size, path.stem.upper()))
	return [path.stem.upper() for path in paths[:count]]

@functools.lru_cache(maxsize=1)
def load_harvest_year_buckets(csv_path: Path = HARVEST_YEAR_BUCKETS_CSV) -> dict[int, int]:
	# Builds original_year → chosen_year from the CSV produced by 0_choose_harvest_years.py.
	# Years below the CSV minimum (pixels whose Faustmann-optimal T* < minimum_harvest_year)
	# are clamped to the smallest chosen representative (floor_year) so that their carbon
	# schedule and bid price are computed at the assigned longer rotation, not the raw T*.
	if not csv_path.exists(): raise FileNotFoundError(f"Run 0_choose_harvest_years.py first: {csv_path}")
	df = pd.read_csv(csv_path, usecols=["original_harvest_year", "chosen_harvest_year"])
	buckets = dict(zip(df["original_harvest_year"].astype(int), df["chosen_harvest_year"].astype(int)))
	floor_year = min(buckets.values())
	for year in range(3, min(buckets)):
		buckets[year] = floor_year
	return buckets

def calculate_harvest_year(k: pd.Series, time_horizon_years: int, discount_rate: float) -> pd.Series:
	harvest_year = pd.Series(float(time_horizon_years + 1), index=k.index)
	for year in range(3, time_horizon_years + 1):
		rule_lhs = ((1 - np.exp(-k*(year - 1))) ** 2 - (1 - np.exp(-k*(year - 2))) ** 2) / ((1 - np.exp(-k*(year - 2))) ** 2).replace(0, np.nan)
		rule_rhs = discount_rate / (1 - (1 + discount_rate) ** (-(year - 1)))
		harvest_year = harvest_year.where(~(rule_lhs > rule_rhs), float(year))
	return harvest_year.map(load_harvest_year_buckets()).fillna(harvest_year).astype(float)

def initialize_smdamage_database(output_dir: Path) -> None:
	db_path = output_dir / SMDAMAGE_DB_FILE
	output_dir.mkdir(parents=True, exist_ok=True)
	with sqlite3.connect(db_path) as conn:
		conn.execute("DROP TABLE IF EXISTS Busch2024_undiscounted_dta_output")
		conn.execute("DROP TABLE IF EXISTS Busch2024_undiscounted_tC_per_h_year")
		conn.execute(f"DROP TABLE IF EXISTS {SMDAMAGE_PIXEL_TABLE}")
		conn.execute(f"DROP TABLE IF EXISTS {SMDAMAGE_YEAR_TABLE}")
		conn.execute(f"CREATE TABLE {SMDAMAGE_PIXEL_TABLE} (country TEXT NOT NULL, pixel_id INTEGER NOT NULL, plantation_genus TEXT, selected_option TEXT, selected_A REAL, selected_k REAL, selected_rotation_year REAL, area_ha REAL, crop_va_USD_per_ha_per_year REAL, selected_establishment_cost_USD_per_ha REAL, p_USD_per_tC_harvested REAL)")
		conn.execute(f"CREATE TABLE {SMDAMAGE_YEAR_TABLE} (country TEXT NOT NULL, pixel_id INTEGER NOT NULL, year INTEGER NOT NULL, tC_per_ha_per_year REAL)")
		conn.execute(f"CREATE INDEX IF NOT EXISTS idx_{SMDAMAGE_PIXEL_TABLE}_country_pixel ON {SMDAMAGE_PIXEL_TABLE} (country, pixel_id)")
		# Note: idx_{SMDAMAGE_YEAR_TABLE}_country_pixel_year is built after all countries
		# are loaded (see __main__) — maintaining it during bulk inserts would cause
		# O(N log N) slowdown as the table grows country by country.

def clear_smdamage_country(conn: sqlite3.Connection, country: str) -> None:
	conn.execute(f"DELETE FROM {SMDAMAGE_PIXEL_TABLE} WHERE country = ?", (country,))
	conn.execute(f"DELETE FROM {SMDAMAGE_YEAR_TABLE} WHERE country = ?", (country,))

def write_smdamage_database(output_dir: Path, pixel_export: pd.DataFrame, annual_export: pd.DataFrame) -> None:
	db_path = output_dir / SMDAMAGE_DB_FILE
	with sqlite3.connect(db_path) as conn:
		countries = pixel_export["country"].dropna().astype(str).unique().tolist()
		for country in countries:
			clear_smdamage_country(conn, country)
		pixel_export.to_sql(SMDAMAGE_PIXEL_TABLE, conn, if_exists="append", index=False)
		annual_export.to_sql(SMDAMAGE_YEAR_TABLE, conn, if_exists="append", index=False)

# Plain-English explanations for dataframe columns used or created in this pipeline.
df_explanation = {
	"id": "Sequential pixel identifier created in this script.",
	"genus": "Selected plantation genus code for the pixel.",
	"area_m2": "Pixel area in square meters from input.",
	"area_ha": "Pixel area in hectares. Original .do variable name after conversion: area.",
	"type": "Input plantation type code used to map to a genus.",
	"biomes": "Biome code used for filtering out excluded biomes.",
	"fao_ecoz": "FAO ecological zone code used in root-to-shoot rules.",
	"continent": "Continent label used for ecological lookups.",
	"griscom": "Baseline binary geographic screen for reforestation suitability (based on Griscom et al. map in the paper workflow); used to include or exclude pixels.",
	"brancalion": "Alternative binary geographic screen for sensitivity analysis (Brancalion tropical restoration feasibility map); used as a substitute for the baseline screen.",
	"bastin": "Alternative binary geographic screen for sensitivity analysis (Bastin global tree restoration potential map); used as a substitute for the baseline screen.",
	"walker": "Alternative binary geographic screen for sensitivity analysis (Walker high unrealized woody restoration potential map); used as a substitute for the baseline screen.",
	"nr_buffer": "Natural regeneration buffer variable from source dataset.",
	"pl_buffer": "Plantation buffer variable from source dataset.",
	"nr_A": "Natural regeneration Chapman-Richards asymptote parameter A.",
	"nr_k": "Natural regeneration Chapman-Richards growth rate parameter k.",
	"exotic": "Country-level share of plantations that are exotic species.",
	
	"nr_rootshoot": "Natural regeneration root-to-shoot ratio.",
	"pl_rootshoot": "Plantation root-to-shoot ratio.",
	"w": "Fraction of carbon at time of harvest that remains stored in long-lived wood products (discounted flow).",
	
	"nr_harvestyear": "Economically selected rotation length proxy for natural regeneration.",
	
	"crop_va": "Annual crop value per hectare used as opportunity cost.",
	"nr_cost": "Natural regeneration establishment or program cost per hectare in 2020 USD.",
	"ep_cost": "Exotic plantation establishment cost per hectare in 2020 USD.",
	"np_cost": "Native plantation establishment cost per hectare in 2020 USD.",
	"p": "Revenue from wood products (net of harvest and delivery costs) as a scalar of carbon at time of harvest.",
	
	"nr_wohrv_total_tC_per_ha": "Natural regeneration total carbon per hectare without harvest over the time horizon. Original .do variable name: nr_wohrv_totalC.",
	"pl_wohrv_total_tC_per_ha": "Plantation total carbon per hectare without harvest. Original .do variable name: pl_wohrv_totalC.",
	"pl_whrv0_total_tC_per_ha": "Plantation total carbon per hectare in the with-harvest scenario for whrv0; in this implementation the carbon equation matches whrv and the distinction is in the economic term. Original .do variable name: pl_whrv0_totalC.",
	"pl_whrv_total_tC_per_ha": "Plantation total carbon per hectare in the with-harvest scenario for whrv; in this implementation the carbon equation matches whrv0 and the distinction is in the economic term. Original .do variable name: pl_whrv_totalC.",
	"pl_npv_estcost_USD_per_ha": "Plantation net present value establishment cost per hectare. Original .do variable name: pl_npv_estcost.",
	"pl_harvested_tC_per_ha": "Plantation harvested carbon per hectare over the time horizon. Original .do variable name: pl_harvested.",
	"nr_wohrv_costeff_USD_per_tCO2": "Natural regeneration abatement cost-effectiveness in USD per ton CO2. Original .do variable name: nr_wohrv_costeff.",
	"pl_wohrv_costeff_USD_per_tCO2": "Plantation abatement cost-effectiveness without harvest in USD per ton CO2. Original .do variable name: pl_wohrv_costeff.",
	"pl_whrv0_costeff_USD_per_tCO2": "Plantation abatement cost-effectiveness with harvest, excluding wood product revenue, in USD per ton CO2. Original .do variable name: pl_whrv0_costeff.",
	"pl_whrv_costeff_USD_per_tCO2": "Plantation abatement cost-effectiveness with harvest, including wood product revenue, in USD per ton CO2. Original .do variable name: pl_whrv_costeff.",
	"refortype_whrv_tCO2_per_USD": "Preferred reforestation type under harvest scenario (P plantation, N natural regeneration). Original .do variable name: refortype_whrv.",
	"mi_whrv_total_tC_per_ha": "Minimum-cost option carbon per hectare under harvest scenario. Original .do variable name: mi_whrv_totalC.",
	"mi_whrv_costeff_USD_per_tCO2": "Minimum-cost option cost-effectiveness under harvest scenario in USD per ton CO2. Original .do variable name: mi_whrv_costeff.",
}

for g in GENUS_ORDER:
	df_explanation[f"{g}_A"] = f"Chapman-Richards asymptote parameter A for {g} plantation genus."
	df_explanation[f"{g}_k"] = f"Chapman-Richards growth rate parameter k for {g} plantation genus."
	df_explanation[f"{g}_harvestyear"] = f"Economically selected harvest rotation year for {g} plantation genus."
	df_explanation[f"{g}_stock_tC_per_ha"] = f"Standing aboveground carbon stock per hectare for {g} plantation genus. Original .do variable name: {g}_stock."
	df_explanation[f"{g}_harvested_tC_per_ha"] = f"Cumulative harvested carbon per hectare for {g} plantation genus. Original .do variable name: {g}_harvested."
	df_explanation[f"{g}_soilC_whrv_tC_per_ha"] = f"Soil carbon per hectare for {g} plantation genus under harvest scenario. Original .do variable name: {g}_soilC_whrv."
	df_explanation[f"{g}_wohrv_total_tC_per_ha"] = f"Total carbon per hectare for {g} plantation genus without harvest. Original .do variable name: {g}_wohrv_totalC."
	df_explanation[f"{g}_whrv0_total_tC_per_ha"] = f"Total carbon per hectare for {g} plantation genus in the with-harvest scenario for whrv0; in this implementation the carbon equation matches whrv and the distinction is in the economic term. Original .do variable name: {g}_whrv0_totalC."
	df_explanation[f"{g}_whrv_total_tC_per_ha"] = f"Total carbon per hectare for {g} plantation genus in the with-harvest scenario for whrv; in this implementation the carbon equation matches whrv0 and the distinction is in the economic term. Original .do variable name: {g}_whrv_totalC."
	df_explanation[f"{g}_npv_estcost_USD_per_ha"] = f"Net present value establishment cost per hectare for {g} plantation genus in USD. Original .do variable name: {g}_npv_estcost."

# Execute one country pipeline from input .dta to SMDAMAGE exports.
def process_country(iso: str, dta_dir: Path, macc_dir: Path) -> dict[str, int]:
	# Find the input paths.
	src = next((c for c in [dta_dir / iso, dta_dir / f"{iso}.dta", dta_dir / f"maps_{iso}.dta"] if c.exists() and c.is_file()), None)
	df = pd.read_stata(src)
	df["id"] = np.arange(1, len(df) + 1)

	# Data cleaning.
	for col in ["griscom", "brancalion", "bastin", "walker", "nr_buffer", "pl_buffer"]:
		if col in df.columns: df[col] = df[col].fillna(0)
		else: df[col] = 0

	for col in ["biomes", "nr_A", "type"]:  # for drop logic
		if col not in df.columns: df[col] = 0.0
	for col in ["nr_cost", "ep_cost", "np_cost", "crop_va"]:
		if col not in df.columns: df[col] = 0.0
	if "fao_ecoz" not in df.columns: df["fao_ecoz"] = np.nan
	# Drop deserts/xeric (biomes=13) and mangroves (biomes=14).
	df = df[df["biomes"] != 13]
	df = df[df["biomes"] != 14]
	df = df[df["nr_A"].notna()]
	df = df[df["type"].notna()]

	# Keep all valid pixels, or one selected pixel when RUN_ALL_PIXELS is False.
	if not RUN_ALL_PIXELS: df = df[df["id"] == TARGET_PIXEL_ID]
	for c in ["nr_cost", "ep_cost", "np_cost"]: df[c] = df[c]*1.1577 # Convert 2011 costs to 2020.

	# Truncate negative A and k values at zero before growth calculations.
	for col in ["nr_A", "nr_k"] + [f"{g}_{suffix}" for g in GENUS_ORDER for suffix in ["A", "k"]]:
		if col in df.columns: df.loc[df[col] < 0, col] = 0

	# Plantation genus
	df["genus"] = df["type"].map(GENUS_BY_TYPE).fillna("")
	df["genus_A"] = np.nan
	df["genus_k"] = np.nan
	for g in GENUS_ORDER:
		mask = df["genus"] == g
		df.loc[mask, "genus_A"] = df.loc[mask, f"{g}_A"]
		df.loc[mask, "genus_k"] = df.loc[mask, f"{g}_k"]
	df["area_ha"] = df["area_m2"] / 10000.0 # Convert area to hectares.
	df.drop(columns=["area_m2"], inplace=True)
	
	# Root-shoot ratio based on IPCC 2019 V4 Ch4 Table 4.4.
	df["nr_rootshoot"] = 0.26
	df["pl_rootshoot"] = 0.26
	df["continent"] = get_continent(iso)
	is_brde_nede = df["genus"].isin(["brde", "nede"])

	for (eco, cont), value in NR_ROOTSHOOT_RULES.items(): df.loc[(df["fao_ecoz"] == eco) & (df["continent"] == cont), "nr_rootshoot"] = value
	for (eco, cont), value in PL_ROOTSHOOT_RULES.items(): df.loc[(df["fao_ecoz"] == eco) & (df["continent"] == cont), "pl_rootshoot"] = value

	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "AMER") & is_brde_nede, "nr_rootshoot"] = 0.466
	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "AMER") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "nr_rootshoot"] = 0.337
	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "ASIA") & is_brde_nede, "nr_rootshoot"] = 0.225
	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "ASIA") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "nr_rootshoot"] = 0.243
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "AMER") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "nr_rootshoot"] = 0.237
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "ASIA") & is_brde_nede, "nr_rootshoot"] = 0.225
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "ASIA") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "nr_rootshoot"] = 0.243

	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "AMER") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "pl_rootshoot"] = 0.203
	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "ASIA") & is_brde_nede, "pl_rootshoot"] = 0.307
	df.loc[(df["fao_ecoz"] == 31) & (df["continent"] == "ASIA") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "pl_rootshoot"] = 0.224
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "AMER") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "pl_rootshoot"] = 0.237
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "ASIA") & is_brde_nede, "pl_rootshoot"] = 0.307
	df.loc[(df["fao_ecoz"] == 32) & (df["continent"] == "ASIA") & df["genus"].isin(["pinu", "cunn", "brev", "neev"]), "pl_rootshoot"] = 0.224

	# Fraction of aboveground carbon at time of harvest stored in long-lived wood products, w (default=0)
	df["w"] = mapped_value(WOOD_PRODUCT_STORAGE_MAP, iso)
	
	# Revenue from wood products (net of harvest and delivery costs) as a scalar of aboveground carbon at time of harvest
	df["p"] = mapped_value(WOOD_PRODUCT_REVENUE_MAP, iso)
	df["exotic"] = mapped_value(EXOTIC_SHARE_MAP, iso)
	df["native"] = 1 - df["exotic"]
	df["nr_npv_estcost_USD_per_ha"] = df["nr_cost"]

	# Pre-loop: compute nr aggregate fields (accum telescoped, soilC, bgC, totalC) needed by all genus breakeven blocks.
	# (Chapman-Richards annual increments telescope: sum_y=1^Y A*[(1-e^{-ky})^2-(1-e^{-k(y-1)})^2] = A*(1-e^{-kY})^2.)
	Years_time_horizon = TIME_HORIZON_YEARS
	df["nr_wohrv_total_tC_per_ha"] = (AGB_C_POOL + BGB_C_POOL*df["nr_rootshoot"])*df["nr_A"]*(1 - np.exp(-df["nr_k"]*Years_time_horizon))**2 + SOIL_C_POOL*Years_time_horizon*(NATURAL_SOIL_C + PLANTATION_SOIL_C)
	# Vectorized annual carbon schedules: nr_annual and pl_annual are (N, T) float32 arrays.
	# Replaces 360 per-year DataFrame columns and ~840 sequential pandas loop iterations.
	N = len(df); T = Years_time_horizon
	years_arr = np.arange(1, T + 1, dtype=np.float32)
	k_nr  = df["nr_k"].to_numpy(dtype=np.float32)
	A_nr  = df["nr_A"].to_numpy(dtype=np.float32)
	rs_nr = df["nr_rootshoot"].to_numpy(dtype=np.float32)
	nr_annual = np.empty((N, T), dtype=np.float32)
	nr_chunk_rows = 120_000
	for i0 in range(0, N, nr_chunk_rows):
		i1 = min(i0 + nr_chunk_rows, N)
		k_ch = k_nr[i0:i1, None]
		A_ch = A_nr[i0:i1, None]
		rs_ch = rs_nr[i0:i1, None]
		nr_cum_ch = ((AGB_C_POOL + BGB_C_POOL*rs_ch)*A_ch*(1 - np.exp(-k_ch*years_arr))**2
		             + SOIL_C_POOL*years_arr*(NATURAL_SOIL_C + PLANTATION_SOIL_C)).astype(np.float32, copy=False)
		nr_annual[i0:i1, 0] = nr_cum_ch[:, 0]
		nr_annual[i0:i1, 1:] = np.diff(nr_cum_ch, axis=1)
	np.nan_to_num(nr_annual, copy=False, nan=0.0)
	pl_annual = np.zeros((N, T), dtype=np.float32)  # filled per genus below
	new_columns: dict[str, np.ndarray] = {}
	new_columns["nr_harvestyear"] = np.full(N, float(T + 1))
	for col in [f"pl_{f}" for f in ["wohrv_total_tC_per_ha", "whrv0_total_tC_per_ha", "whrv_total_tC_per_ha", "npv_estcost_USD_per_ha", "harvested_tC_per_ha"]]:
		new_columns[col] = np.full(N, np.nan)
	new_columns["selected_plantation_rotation_year"] = np.full(N, np.nan)
	new_columns["nr_wohrv_costeff_USD_per_tCO2"] = np.full(N, np.nan)
	new_columns["pl_wohrv_costeff_USD_per_tCO2"] = np.full(N, np.nan)
	new_columns["pl_whrv0_costeff_USD_per_tCO2"] = np.full(N, np.nan)
	new_columns["pl_whrv_costeff_USD_per_tCO2"] = np.full(N, np.nan)
	new_columns["refortype_whrv_tCO2_per_USD"] = np.full(N, "", dtype=object)
	new_columns["mi_whrv_total_tC_per_ha"] = np.full(N, np.nan)
	new_columns["mi_whrv_costeff_USD_per_tCO2"] = np.full(N, np.nan)
	df = pd.concat([df, pd.DataFrame(new_columns, index=df.index)], axis=1)

	# Calculate natural regeneration "nr" harvest year (Faustmann-style rule; used only for nr_harvestyear column, later dropped).
	# JFR: Plan is to use harvestyear as the length of a contract in SMDAMAGE.
	discount_rate_for_harvest = DISCOUNT_RATE # Should be used only for choosing the harvest year.
	df["nr_harvestyear"] = calculate_harvest_year(df["nr_k"], Years_time_horizon, discount_rate_for_harvest)

	# Discounted present value of establishment costs.
	if "crop_va" not in df.columns: df["crop_va"] = 0.0
	oppcost_discount_sum = float(np.sum((1.0 - DISCOUNT_RATE) ** (np.arange(1, T + 1, dtype=np.float64) - 1.0)))

	for g in GENUS_ORDER:  # Chunked vectorization: genus-wide, but processed in row blocks.
		mask = df["genus"] == g
		if not mask.any(): continue
		g_A_s = df.loc[mask, f"{g}_A"]
		g_k_s = df.loc[mask, f"{g}_k"]
		g_harvestyear = calculate_harvest_year(g_k_s, Years_time_horizon, discount_rate_for_harvest)
		if g == "pinu": g_npv_init = (df.loc[mask, "exotic"]*df.loc[mask, "ep_cost"] + df.loc[mask, "native"]*df.loc[mask, "np_cost"]).to_numpy()
		elif g == "cunn": g_npv_init = (df.loc[mask, "np_cost"] if iso == "CHN" else df.loc[mask, "ep_cost"]).to_numpy()
		elif g == "euca": g_npv_init = df.loc[mask, "ep_cost"].to_numpy()
		else: g_npv_init = (df.loc[mask, "exotic"]*df.loc[mask, "ep_cost"] + df.loc[mask, "native"]*df.loc[mask, "np_cost"]).to_numpy()
		rows = np.flatnonzero(mask.to_numpy())
		A1d = g_A_s.to_numpy(dtype=np.float32)
		k1d = g_k_s.to_numpy(dtype=np.float32)
		hy1d = g_harvestyear.to_numpy(dtype=np.float32)
		hy1d_int = np.maximum(hy1d.astype(np.int32), 1)
		rs1d = df.loc[mask, "pl_rootshoot"].to_numpy(dtype=np.float32)
		w1d = df.loc[mask, "w"].to_numpy(dtype=np.float32)
		g_sf = np.empty(len(rows), dtype=np.float32)
		g_hf = np.empty(len(rows), dtype=np.float32)
		harvest_counts = np.empty(len(rows), dtype=np.int16)
		yr = years_arr[None, :]
		chunk_rows = 100_000
		for c0 in range(0, len(rows), chunk_rows):
			c1 = min(c0 + chunk_rows, len(rows))
			A_ch = A1d[c0:c1, None]
			k_ch = k1d[c0:c1, None]
			hy_ch = hy1d[c0:c1, None]
			rs_ch = rs1d[c0:c1, None]
			w_ch = w1d[c0:c1, None]
			yr_mod = np.mod(yr, hy_ch)
			harvest = (yr_mod == 0)
			g_stock_2d = (A_ch*(1 - np.exp(-k_ch*yr_mod))**2).astype(np.float32, copy=False)
			harv_c = (A_ch*(1 - np.exp(-k_ch*yr))**2).astype(np.float32, copy=False)
			harv_c *= harvest
			harv_c *= ((1.0 - DISCOUNT_RATE) ** (yr - 1.0)).astype(np.float32, copy=False)
			np.cumsum(harv_c, axis=1, out=harv_c)
			g_soil_2d = (PLANTATION_SOIL_C*np.minimum(np.maximum(hy_ch - 1.0, 0.0), yr)).astype(np.float32, copy=False)
			g_cum_2d = g_stock_2d
			g_cum_2d *= (1.0 + rs_ch)
			g_cum_2d += g_soil_2d
			g_cum_2d += w_ch*harv_c
			pl_g = np.empty_like(g_cum_2d, dtype=np.float32)
			pl_g[:, 0] = g_cum_2d[:, 0]
			pl_g[:, 1:] = np.diff(g_cum_2d, axis=1)
			np.nan_to_num(pl_g, copy=False, nan=0.0)
			pl_annual[rows[c0:c1], :] = pl_g
			g_sf[c0:c1] = g_stock_2d[:, -1]
			g_hf[c0:c1] = harv_c[:, -1]
			harvest_counts[c0:c1] = harvest.sum(axis=1).astype(np.int16, copy=False)
		# Scalar fields for cost-effectiveness (final-year values).
		g_sf_soil = PLANTATION_SOIL_C * np.minimum(np.maximum(hy1d - 1.0, 0.0), float(T))
		max_cycles = int(np.max(np.floor_divide(T, hy1d_int))) if len(hy1d_int) else 0
		if max_cycles > 0:
			m = np.arange(1, max_cycles + 1, dtype=np.int32)
			harvest_years = hy1d_int[:, None] * m[None, :]
			valid = harvest_years <= T
			weights = (1.0 - DISCOUNT_RATE) ** (harvest_years.astype(np.float64) - 1.0)
			g_npv_mult = np.prod(np.where(valid, 1.0 + weights, 1.0), axis=1)
			g_npv_f = g_npv_init * g_npv_mult
		else:
			g_npv_f = g_npv_init
		g_wohrv_total = (AGB_C_POOL*A1d*(1 - np.exp(-k1d*T))**2
		               + BGB_C_POOL*(A1d*(1 - np.exp(-k1d*T))**2)*rs1d + SOIL_C_POOL*T*PLANTATION_SOIL_C)
		g_whrv_total  = (AGB_C_POOL*g_sf + BGB_C_POOL*g_sf*rs1d + SOIL_C_POOL*g_sf_soil + HARVEST_C_POOL*w1d*g_hf)
		df.loc[mask, "pl_wohrv_total_tC_per_ha"] = g_wohrv_total
		df.loc[mask, "pl_whrv0_total_tC_per_ha"] = g_whrv_total
		df.loc[mask, "pl_whrv_total_tC_per_ha"]  = g_whrv_total
		df.loc[mask, "pl_npv_estcost_USD_per_ha"] = g_npv_f
		df.loc[mask, "pl_harvested_tC_per_ha"]   = g_hf
		df.loc[mask, "selected_plantation_rotation_year"] = g_harvestyear
	
	# Compute cost-effectiveness in $/tCO2 from per-hectare costs and per-hectare carbon.
	df["nr_wohrv_costeff_USD_per_tCO2"] = (df["crop_va"]*oppcost_discount_sum + df["nr_cost"]) / (3.67*df["nr_wohrv_total_tC_per_ha"]).replace(0, np.nan)
	df["pl_wohrv_costeff_USD_per_tCO2"] = (df["crop_va"]*oppcost_discount_sum + df["pl_npv_estcost_USD_per_ha"]) / (3.67*df["pl_wohrv_total_tC_per_ha"]).replace(0, np.nan)
	df["pl_whrv0_costeff_USD_per_tCO2"] =(df["crop_va"]*oppcost_discount_sum + df["pl_npv_estcost_USD_per_ha"]) / (3.67*df["pl_whrv0_total_tC_per_ha"]).replace(0, np.nan)
	df["pl_whrv_costeff_USD_per_tCO2"] = (df["crop_va"]*oppcost_discount_sum + df["pl_npv_estcost_USD_per_ha"] - df["p"]*df["pl_harvested_tC_per_ha"]) / (3.67*df["pl_whrv_total_tC_per_ha"]).replace(0, np.nan)
	
	# Compare plantation vs natural regeneration for whrv scenario.
	lhs_nr_tCO2_per_USD = 3.67*df["nr_wohrv_total_tC_per_ha"] / (df["crop_va"]*oppcost_discount_sum + df["nr_cost"]).replace(0, np.nan)
	lhs_pl_wh_tCO2_per_USD = 3.67*df["pl_whrv_total_tC_per_ha"] / (df["crop_va"]*oppcost_discount_sum + df["pl_npv_estcost_USD_per_ha"] - df["p"]*df["pl_harvested_tC_per_ha"]).replace(0, np.nan)
	
	# Determine minimum cost-effectiveness (plantation vs natural regeneration).
	df["refortype_whrv_tCO2_per_USD"] = np.where(lhs_pl_wh_tCO2_per_USD > lhs_nr_tCO2_per_USD, "P", np.where(lhs_pl_wh_tCO2_per_USD < lhs_nr_tCO2_per_USD, "N", "."))
	df.loc[lhs_pl_wh_tCO2_per_USD < 0, "refortype_whrv_tCO2_per_USD"] = "P"
	mi_counts = {"refortype_dot_total": int((df["refortype_whrv_tCO2_per_USD"] == ".").sum()),}
	for col in ["nr_wohrv_total_tC_per_ha", "pl_whrv_total_tC_per_ha", "crop_va", "nr_cost", "pl_npv_estcost_USD_per_ha", "p", "pl_harvested_tC_per_ha"]:
		mi_counts[f"{col}_dot_null_or_nan"] = int(df.loc[df["refortype_whrv_tCO2_per_USD"] == ".", col].isna().sum())

	# Generate minimum output columns (keep only whrv scenario for MACC).
	df.loc[:, "mi_whrv_total_tC_per_ha"] = np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["pl_whrv_total_tC_per_ha"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", df["nr_wohrv_total_tC_per_ha"], 0))
	df.loc[:, "mi_whrv_costeff_USD_per_tCO2"] = np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["pl_whrv_costeff_USD_per_tCO2"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", df["nr_wohrv_costeff_USD_per_tCO2"], np.nan))

	# Avoid allocating a third full (N,T) matrix for mi_annual on very large countries.
	is_P_1d = (df["refortype_whrv_tCO2_per_USD"].to_numpy() == "P")
	is_N_1d = (df["refortype_whrv_tCO2_per_USD"].to_numpy() == "N")

	# SMDAMAGE doesn't need the MACC curves, so I've omitted this code.
	# Print all columns as one item/value per row.
	# item_value_df = df.rename_axis("row").reset_index().melt(id_vars="row", var_name="item", value_name="value")
	# print(item_value_df.to_string(index=False))

	# Diagnose cost-effectiveness values before binning.
	# print(df[["mi_whrv_costeff_USD_per_tCO2", "mi_whrv_total_tC_per_ha", "refortype_whrv_tCO2_per_USD", "area_ha"]].to_string())

	# MARGINAL ABATEMENT COST CURVE bins in $/tCO2: sum area in each 5-unit bin.
	# price_bins = list(range(0, 201, 5))
	# macc_curve = {p: 0.0 for p in price_bins}
	# Price_per_tCO2 = df["mi_whrv_costeff_USD_per_tCO2"]
	# area_ha = df["area_ha"].fillna(0)
	# Negative cost-effectiveness means wood revenue exceeds costs; treat as $0/tCO2.
	# macc_curve[0] += area_ha.where(Price_per_tCO2 <= 0, 0).sum(skipna=True)
	# # Example: area with 15 < price <= 20 is added to macc_curve[20].
	# for p in price_bins[1:]:
	# 	mask = (Price_per_tCO2 > p - 5) & (Price_per_tCO2 <= p)
	# 	macc_curve[p] += area_ha.where(mask, 0).sum(skipna=True)

	# macc = pd.DataFrame({"price_per_tCO2": list(macc_curve.keys()), "area_ha": list(macc_curve.values())})
	# # Save MAC curves and map-ready outputs.
	# macc_dir.mkdir(parents=True, exist_ok=True)
	# macc.to_csv(macc_dir / f"MACC_{iso}.csv", index=False)

	# Map model outputs into a wide SMDAMAGE-style export.
	# - plantation_genus: fixed plantation genus available on the pixel.
	# - selected_option: best model choice between plantation and natural regeneration.
	# - selected_A / selected_k / selected_rotation_year: parameters for the chosen option.
	#   Natural regeneration uses Years_time_horizon as the contract/rotation length in this export.
	# - selected_establishment_cost_USD_per_ha: model-used establishment cost for the chosen option.
	# - p_USD_per_tC_harvested: wood-product revenue scalar, zeroed when the selected option has no harvest revenue.
	selected_option = df["refortype_whrv_tCO2_per_USD"].map({"P": "plantation", "N": "natural_regeneration", ".": "undetermined"})
	selected_rotation_year = np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["selected_plantation_rotation_year"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", float(Years_time_horizon), np.nan))
	macc_dir.mkdir(parents=True, exist_ok=True)

	smdamage_export = pd.DataFrame({"country": iso, "pixel_id": df["id"], "plantation_genus": df["genus"], "selected_option": selected_option,
		"selected_A": np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["genus_A"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", df["nr_A"], np.nan)),
		"selected_k": np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["genus_k"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", df["nr_k"], np.nan)),
		"selected_rotation_year": selected_rotation_year, "area_ha": df["area_ha"], "crop_va_USD_per_ha_per_year": df["crop_va"],
		"selected_establishment_cost_USD_per_ha": np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["pl_npv_estcost_USD_per_ha"], np.where(df["refortype_whrv_tCO2_per_USD"] == "N", df["nr_cost"], np.nan)),
		"p_USD_per_tC_harvested": np.where(df["refortype_whrv_tCO2_per_USD"] == "P", df["p"], 0.0),})
	if SKIP_SQLITE_EXPORT: print(f"[SKIP_SQLITE_EXPORT] {iso}", flush=True)
	else:
		db_path = macc_dir / SMDAMAGE_DB_FILE
		with sqlite3.connect(db_path) as conn:
			conn.execute("PRAGMA synchronous = OFF")   # safe for a data-load script; 5-10x faster writes
			conn.execute("PRAGMA cache_size = -131072") # 128 MB page cache
			clear_smdamage_country(conn, iso)
			smdamage_export.to_sql(SMDAMAGE_PIXEL_TABLE, conn, if_exists="append", index=False)
			# Annual write: per-year executemany with .tolist() — vectorized, O(N) peak memory per year.
			sel_rot = np.where(np.isnan(selected_rotation_year), -1.0, selected_rotation_year)
			pixel_ids_arr = df["id"].to_numpy()
			insert_sql = f"INSERT INTO {SMDAMAGE_YEAR_TABLE} (country, pixel_id, year, tC_per_ha_per_year) VALUES (?,?,?,?)"
			for yr_idx in range(T):
				year = yr_idx + 1
				ym = sel_rot >= float(year)
				if not ym.any(): continue
				p_mask = is_P_1d[ym]
				n_mask = is_N_1d[ym]
				vals = nr_annual[ym, yr_idx].copy()
				vals[p_mask] = pl_annual[ym, yr_idx][p_mask]
				vals[~(p_mask | n_mask)] = 0.0
				pids = pixel_ids_arr[ym].tolist()   # one C-level numpy→Python call, not per-row Python
				conn.executemany(insert_sql, zip([iso]*len(pids), pids, [year]*len(pids), vals.tolist()))

	# Show carbon buckets.
	# total_C_categories = {}
	# for total_carbon in df[mi_year_cols].sum(axis=1):
	# 	bucket = round(total_carbon, 0)
	# 	total_C_categories[bucket] = total_C_categories.get(bucket, 0) + 1
	# print(dict(sorted(total_C_categories.items())))

	mode_label = "all pixels" if RUN_ALL_PIXELS else f"pixel {TARGET_PIXEL_ID}"
	print(f"[OK] {iso} {mode_label}", flush=True)
	# print(f"[MI_COUNTS] {iso} {mi_counts}", flush=True)
	return mi_counts

# Iterate across requested ISO codes and run the country pipeline.
def main() -> None:
	parser = argparse.ArgumentParser(description="Python conversion of 1. Model loop all data.do")
	parser.add_argument("--dta-dir", type=Path, required=True, help="Directory containing per-country .dta input files",)
	parser.add_argument("--macc-dir", type=Path, required=True, help="Directory to write MACC_*.csv files")
	parser.add_argument("--iso", nargs="*", help="Optional ISO code filter. If omitted, run all countries in the input directory.")
	parser.add_argument("--smallest-n", type=int, help="Optional count of smallest .dta files to process by file size.")
	args = parser.parse_args()
	requested_isos = sorted(iso.upper() for iso in args.iso) if args.iso else iter_smallest_input_isos(args.dta_dir, args.smallest_n) if args.smallest_n else iter_input_isos(args.dta_dir)
	initialize_smdamage_database(args.macc_dir)
	all_blank_counts: dict[str, dict[str, int]] = {}
	for iso in requested_isos: all_blank_counts[iso] = process_country(iso=iso, dta_dir=args.dta_dir, macc_dir=args.macc_dir)

if __name__ == "__main__":
	# Set this to True to run all countries from in-script settings (no CLI args).
	
	base_dir = Path(__file__).resolve().parent.parent  # Busch2024/
	db_dir = base_dir / "Output" / "Databases"  # matches DEFAULT_DB_FILE in 2_k_means_carbon_removal.py
	db_path = db_dir / SMDAMAGE_DB_FILE
	dta_dir = base_dir / "Input"
	cutoff_src = next((c for c in [dta_dir / RESUME_AFTER_ISO, dta_dir / f"{RESUME_AFTER_ISO}.dta", dta_dir / f"maps_{RESUME_AFTER_ISO}.dta"] if c.exists() and c.is_file()), None)
	if cutoff_src is None: raise FileNotFoundError(f"{RESUME_AFTER_ISO} input file not found in {dta_dir}")
	cutoff_size = cutoff_src.stat().st_size
	requested_isos = [path.stem.upper() for path in sorted((path for path in dta_dir.glob("*.dta") if path.is_file() and path.stat().st_size > cutoff_size), key=lambda path: (path.stat().st_size, path.stem.upper()))]
	if db_path.exists(): print(f"Resume mode: assuming all countries up to {RESUME_AFTER_ISO} ({cutoff_size/1e6:.1f} MB) are complete; skipping DB completeness checks.", flush=True)
	else:
		print(f"No existing {db_path.name}; creating a fresh database.", flush=True)
		initialize_smdamage_database(db_dir)
	print(f"Processing {len(requested_isos)} countries with .dta size > {RESUME_AFTER_ISO}.", flush=True)
	all_blank_counts: dict[str, dict[str, int]] = {}
	for iso in requested_isos:
		src = next((c for c in [dta_dir / iso, dta_dir / f"{iso}.dta", dta_dir / f"maps_{iso}.dta"] if c.exists() and c.is_file()), None)
		size_mb = src.stat().st_size / 1e6 if src else 0
		t0 = time.perf_counter()
		all_blank_counts[iso] = process_country(iso=iso, dta_dir=dta_dir, macc_dir=db_dir)
		elapsed = time.perf_counter() - t0
		print(f"  {elapsed:.1f}s / {size_mb:.1f} MB = {elapsed/size_mb:.2f} s/MB", flush=True)
	
	print("Building year table index...", flush=True)
	with sqlite3.connect(db_path) as _c:
		_c.execute("PRAGMA synchronous = OFF")
		_c.execute(f"CREATE INDEX IF NOT EXISTS idx_{SMDAMAGE_YEAR_TABLE}_country_pixel_year ON {SMDAMAGE_YEAR_TABLE} (country, pixel_id, year)")
	print("Index built.", flush=True)
	# print(f"[MI_COUNTS_SUMMARY] {all_blank_counts}", flush=True)