# 1a_import_Busch2024_to_SMDAMAGE.py — Written by JFR and CoPilot (mostly Claude), 2026-07-14.

# Purpose: Busch2024_to_SMDAMAGE.sqlite is the data bridge between the Busch 2024 paper ".dta" files and SMDAMAGE.
# Each pixel in each .dta file is treated as a bidder. Each bidder chooses a most profitable crop
# (natural regeneration or some plantation crop), the associated carbon removal schedule and a bid price to the SMDAMAGE auction.
# But 89 million bidders is too big for SMDAMAGE, so I use a k-means to cluster similar bidders into groups.
# Later in the workflow, SMDAMAGE project file create_database.py reads Busch2024_to_SMDAMAGE.sqlite
# and loads forestry bidders, one per group, into the SMDAMAGE auction.

# Despite repeatedly nagging Claude to make it faster and use less memory, the code takes over an hour to run 
# on my HP Envy laptop and is likely to run out of memory in the process. Hence the re-start option. 
# I set it to run by .dta input file size increasing, so at least you can see progress.

# Origin: I adapted this code from "1. Model loop all data corrected.do", Stata code published by Busch et al,
# "Cost-effectiveness of natural forest regeneration and plantations for climate mitigation" (2024).
# That Stata code reads per-country .dta input files, applies biome and geographic filters,
# computes Chapman-Richards carbon growth curves under natural regeneration and plantation scenarios,
# applies IPCC root-to-shoot ratios and FAO ecozone rules, evaluates cost-effectiveness per pixel
# in $/tCO2, and selects the least-cost reforestation option for each pixel.

# This version replaces the Busch et al harvest-year selection with a bid_score approach.
# For each pixel, the winning option and contract length minimise bid / warming ($/°C cooling),
# where bid = establishment_cost + discounted_opportunity_cost (- discounted_harvest_NPV for plantations)
# and warming = convolution of annual carbon sequestration with the Hector climate impulse response.
 
# Input:
# Input/*.dta published by Busch et al as the replication dataset for the 2024 paper.
# Not generated by any script in this repo; download from the paper’s data repository.
# Each .dta file contains pixel information on one country. One row per pixel with
# Chapman-Richards growth parameters (A, k) for natural regeneration and each plantation
# genus, establishment costs, crop opportunity value, area, biome, FAO ecozone, and
# geographic screen variables (griscom, brancalion, bastin, walker).
#
# TODO, this is out of date. Output: Output/Databases/Busch2024_to_SMDAMAGE.sqlite, two tables:
# Undiscounted_dta_output, one row per pixel:
# country, pixel_id, option (NR or plantation genus), best_contract_length,
# bid (USD/ha at best_contract_length), bid_score (int, bid/warming at best_contract_length),
# area_ha, crop_va_USD_per_ha_per_year.
# tC_per_h_per_year, one row per pixel per year (year 0 … best_contract_length-1):
# country, pixel_id, year, tC_per_ha_per_year.
#
# Downstream pipeline (later scripts add further tables to the same SQLite file):
# 2_k_means_carbon_removal.py — clusters pixels on their carbon profiles within each contract
# length; writes cluster centre schedules (carbon_removal_schedules) and assigns each pixel
# a cluster_index (added as a column on Undiscounted_dta_output).
# 3_import_k_means_csv_to_sqlite.py — loads k-means CSV results into the database.
# 4_move_Busch_data_to_SMDAMAGE.py — computes per-pixel NPV bid costs and builds area-share
# bid-step supply curves (forestry_bid_curves), one curve per (contract_length, cluster_index).

from __future__ import annotations
import csv
import time
from pathlib import Path
import numpy as np
import pandas as pd # pandas allows chunked reading of the very large files, lowering memory requirements.

DISCOUNT_RATE = 0.03 # Contract length is chosen using this rate.

DTA_DIR  = Path(__file__).resolve().parent.parent / "Input"
OUTPUT_CSV_DIR = Path(__file__).resolve().parent.parent / "Output" / "Databases"
UNDISCOUNTED_CSV_PREFIX = "undiscounted_contracts" # Output CSV files: one per contract length.

TARGET_PIXEL_ID = 5119
RUN_ONLY_ONE_PIXEL = False
GENUS_ORDER = ["pinu", "cunn", "euca", "brde", "brev", "nede", "neev"]
GENUS_BY_TYPE = {1: "neev", 2: "brev", 3: "brde", 4: "neev", 5: "cunn", 6: "euca", 7: "nede", 8: "neev", 9: "pinu", 10: "brde", 11: "neev", 12: "brde", 13: "brev", 14: "brde", 15: "neev"}
_GENUS_LOOKUP = np.array([""] * 16, dtype=object) # numpy lookup for type→genus; replaces Python dict loop per pixel.
for _k, _v in GENUS_BY_TYPE.items(): _GENUS_LOOKUP[_k] = _v

# In the Chapman-Richards growth function, A is the asymptotic growth peak and k is the % growth per year.
KEEP_COLS = {"biomes", "nr_A", "nr_k", "type", "fao_ecoz", "area_m2", "nr_cost", "ep_cost", "np_cost", "crop_va", "griscom", "brancalion", "bastin", "walker", "nr_buffer", "pl_buffer"} | {f"{g}_{s}" for g in GENUS_ORDER for s in ["A", "k"]}
CLAMP_COLS = ["nr_A", "nr_k"] + [f"{g}_{s}" for g in GENUS_ORDER for s in ["A", "k"]] # Precomputed to avoid per-chunk list construction.
KEEP_FOR_OUTPUT = {"id", "nr_A", "nr_k", "nr_rootshoot", "pl_rootshoot", "area_ha", "crop_va"} | {f"{g}_{s}" for g in GENUS_ORDER for s in ["A", "k"]} # Columns needed for SQLite output; all others dropped before valid-mask filter.
# TIME_HORIZON_YEARS = 120 # Must cover the full contract-length range (lengths goes to 115).
AUSTMANN_F = 1
NATURAL_SOIL_C = 0.415107735
PLANTATION_SOIL_C = 0.092749069
AGB_C_POOL = 1
BGB_C_POOL = 1
SOIL_C_POOL = 1
HARVEST_C_POOL = 1
SMALL_DTA_COUNT = 50
CHUNK_SIZE = 20_000

AFRI = {"DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "COG", "CIV", "COD", "DJI", "EGY", "GNQ",
	"ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "LBY", "MDG", "MWI", "MDV", "MLI", "MRT", "MUS",
	"MAR", "MOZ", "NAM", "NER", "NGA", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TZA", "TGO", "TUN", "UGA",
	"ESH", "ZMB", "ZWE"}
AMER = {"ATG", "ARG", "BRB", "BLZ", "BOL", "BRA", "CHL", "COL", "CRI", "CUB", "DMA", "DOM", "ECU", "SLV", "GUF", "GRD", "GTM",
	"GUY", "HTI", "HND", "JAM", "MEX", "NIC", "PAN", "PRY", "PER", "KNA", "LCA", "VCT", "SUR", "TTO", "URY", "VEN"}
ASIA = {"AFG", "BGD", "BTN", "KHM", "CHN", "COK", "PRK", "FJI", "IND", "IDN", "IRN", "IRQ", "JOR", "KAZ", "KIR", "KGZ", "LAO",
	"LBN", "MYS", "MHL", "FSM", "MNG", "MMR", "NRU", "NPL", "OMN", "PAK", "PLW", "PSE", "PNG", "PHL", "WSM", "SLB", "LKA", "SYR",
	"TJK", "THA", "TLS", "TKL", "TON", "TKM", "TUV", "UZB", "VUT", "VNM", "YEM", "ARM", "AZE", "GEO", "TUR"}

NR_ROOTSHOOT_RULES = {(11, "AFRI"): 0.825, (11, "AMER"): 0.221, (11, "ASIA"): 0.207, (12, "AFRI"): 0.232, (12, "AMER"): 0.2845, (12, "ASIA"): 0.323,
	(13, "AFRI"): 0.332, (13, "AMER"): 0.334, (13, "ASIA"): 0.440, (16, "AMER"): 0.348, (16, "ASIA"): 0.322, (21, "AFRI"): 0.232, (21, "AMER"): 0.175,
	(21, "ASIA"): 0.230, (22, "AMER"): 0.336, (22, "ASIA"): 0.440, (23, "AMER"): 1.338, (23, "ASIA"): 1.338}
PL_ROOTSHOOT_RULES = {(11, "AMER"): 0.170, (11, "ASIA"): 0.325, (16, "AMER"): 2.158, (23, "ASIA"): 2.158}
NR_ROOTSHOOT = {c: {eco: v for (eco, cc), v in NR_ROOTSHOOT_RULES.items() if cc == c} for c in ("AFRI", "AMER", "ASIA")} # Continent-filtered rootshoot lookup; avoids per-chunk branch checking.
PL_ROOTSHOOT = {c: {eco: v for (eco, cc), v in PL_ROOTSHOOT_RULES.items() if cc == c} for c in ("AFRI", "AMER", "ASIA")}

WOOD_PRODUCT_STORAGE_MAP = {0.188: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "MEX", "NIC", "PAN", "SLV", "TTO", "VCT"},
	0.268: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PER", "PRY", "SUR", "URY", "VEN"},
	0.355: {"AFG", "ARM", "AZE", "BGD", "BTN", "CHN", "GEO", "IDN", "IND", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "KHM", "LAO", "LBN", "LKA", "MMR", "MNG", "MYS", "NPL", "OMN", "PAK", "PHL", "PNG", "PRK", "PSE", "SYR", "THA", "TJK", "TKM", "TLS", "TUR", "UZB", "VNM", "YEM"},
	0.392: {"AGO", "BDI", "BEN", "BFA", "BWA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "DZA", "EGY", "ERI", "ESH", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "LBY", "LSO", "MAR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NAM", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SWZ", "SYC", "TCD", "TGO", "TUN", "TZA", "UGA", "ZAF", "ZMB", "ZWE"},
	0.415: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}}
WOOD_PRODUCT_REVENUE_MAP = {52.65: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "NIC", "PAN", "SLV", "TTO", "VCT"},
	59.73: {"MEX"}, 61.04: {"BOL", "BRA", "COL", "ECU", "GUF", "GUY", "PER", "SUR", "VEN"}, 67.76: {"BGD", "IDN", "KHM", "LAO", "LKA", "MMR", "MYS", "OMN", "PHL", "PNG", "THA", "TLS", "VNM", "YEM"},
	69.26: {"PRY"}, 71.24: {"AGO", "BDI", "BEN", "BFA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "ERI", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SYC", "TCD", "TGO", "TZA", "UGA", "ZMB", "ZWE"},
	76.08: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}, 76.88: {"IND"}, 80.003: {"ARG", "CHL", "URY"}, 80.83: {"BWA", "NAM"},
	88.84: {"AFG", "ARM", "AZE", "BTN", "CHN", "GEO", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "MNG", "NPL", "PAK", "PRK", "PSE", "SYR", "TJK", "TKM", "TUR", "UZB"},
	93.40: {"DZA", "EGY", "ESH", "LBY", "LSO", "MAR", "SWZ", "TUN", "ZAF"}}
EXOTIC_SHARE_MAP = {0.74: {"AGO", "BWA", "COM", "DJI", "ERI", "SWZ", "ETH", "KEN", "LSO", "MDG", "MWI", "MDV", "MUS", "MOZ", "NAM", "SYC", "SOM", "ZAF", "SSD", "SDN", "TZA", "UGA", "ZMB", "ZWE", "BEN", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COG", "CIV", "COD", "GNQ", "GAB", "GMB", "GHA", "GIN", "GNB", "LBR", "MLI", "MRT", "NER", "NGA", "RWA", "STP", "SEN", "SLE", "TGO"},
	0.50: {"DZA", "EGY", "LBY", "MAR", "TUN", "ESH"}, 0.31: {"CHN", "PRK", "MNG"}, 0.40: {"BGD", "BTN", "KHM", "IND", "IDN", "LAO", "MYS", "MMR", "NPL", "PAK", "PHL", "LKA", "THA", "TLS", "VNM"},
	0.05: {"AFG", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "OMN", "PSE", "SYR", "TJK", "TKM", "UZB", "YEM", "ARM", "AZE", "GEO", "TUR"},
	0.78: {"COK", "FJI", "KIR", "MHL", "FSM", "NRU", "PLW", "PNG", "WSM", "SLB", "TKL", "TON", "TUV", "VUT"}, 0.32: {"ATG", "BRB", "CUB", "DMA", "DOM", "GRD", "HTI", "KNA", "LCA", "VCT", "TTO"},
	0.18: {"BLZ", "CRI", "SLV", "GTM", "HND", "JAM", "MEX", "NIC", "PAN"}, 0.97: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"}}

def get_continent(iso: str) -> str: return "AFRI" if iso in AFRI else "AMER" if iso in AMER else "ASIA" if iso in ASIA else ""
def mapped_value(mapping: dict[float, set[str]], iso: str, default: float = 0.0) -> float: return next((value for value, isos in mapping.items() if iso in isos), default)
def iter_input_isos(dta_dir: Path) -> list[str]: return sorted(path.stem.upper() for path in dta_dir.glob("*.dta") if path.is_file())
def iter_smallest_input_isos(dta_dir: Path, count: int) -> list[str]: return [path.stem.upper() for path in sorted((path for path in dta_dir.glob("*.dta") if path.is_file()), key=lambda path: (path.stat().st_size, path.stem.upper()))[:count]]

# Hector impulse-response: warming per unit carbon emission (°C per GtC) for years 1–296,
# from smdamage_data.db table warming_factors, row hector_name='ffi_emissions', emission_factor=1.0,
# retrieved 2026-07-15.  Index t gives the warming in year t from a 1 GtC pulse at year 0.
W_Carbon_T = np.array([
	0.0, 0.000810628, 0.001371235, 0.001782009, 0.002046314, 0.002224353, 0.002351114, 0.002443458, 0.002509201, 0.002558329, 0.002590824, 0.002611596, 0.002625164, 0.002629826, 0.002629549, 0.002626513, 0.002621047, 0.002608917, 0.002594681, 0.002581921, 0.00256672, 0.002547936, 0.002530647, 0.002513368, 0.00249398, 0.002474633, 0.002454967, 0.002435273, 0.00241557, 0.002397998, 0.002380466, 0.002362705,
	0.002345028, 0.002325004, 0.002313421, 0.002298453, 0.002283075, 0.002267619, 0.002249917, 0.002236422, 0.002219432, 0.00220099, 0.002179592, 0.002164619, 0.002147621, 0.002130811, 0.002120102, 0.002102948, 0.002091885, 0.002081073, 0.002066112, 0.00205582, 0.002037398, 0.002026768, 0.002014009, 0.002005162, 0.001998105, 0.001989367, 0.001978528, 0.001968593, 0.001960273, 0.001949699, 0.001941456, 0.001931482,
	0.00192284, 0.001914272, 0.001906424, 0.001900075, 0.001892102, 0.001885921, 0.001879774, 0.001869948, 0.001863941, 0.001855957, 0.001851842, 0.001841667, 0.001833609, 0.001829512, 0.001821593, 0.001815792, 0.001809341, 0.001803371, 0.00179802, 0.001789594, 0.001785239, 0.001777986, 0.001771512, 0.001765262, 0.001760534, 0.001754719, 0.001747698, 0.001742777, 0.001737629, 0.001728559, 0.001722733, 0.001712962,
	0.001708024, 0.001697598, 0.001691429, 0.001685464, 0.001681741, 0.001676029, 0.001668527, 0.001662831, 0.001657143, 0.00164965, 0.001646093, 0.001638629, 0.001632972, 0.001629437, 0.001621997, 0.001616362, 0.001608937, 0.001603635, 0.001598023, 0.001594534, 0.001589255, 0.001583666, 0.001578084, 0.001572828, 0.001565463, 0.00156202, 0.001556469, 0.001551242, 0.001543907, 0.001538378, 0.00153529, 0.001529776,
	0.00152427, 0.001523305, 0.001518089, 0.001510763, 0.001507365, 0.001500057, 0.001496675, 0.001489385, 0.00148422, 0.001480862, 0.001475714, 0.001468133, 0.001463001, 0.001457875, 0.001454554, 0.001445525, 0.001444018, 0.001438922, 0.001431714, 0.001428429, 0.001421234, 0.001414416, 0.001409025, 0.001403961, 0.001398582, 0.00139353, 0.001388486, 0.001383127, 0.001378101, 0.001373081, 0.001365947, 0.001360937,
	0.001355637, 0.001350664, 0.00134358, 0.001340419, 0.001333678, 0.001328422, 0.001323499, 0.001322499, 0.001313676, 0.001306657, 0.001303562, 0.001298673, 0.001291687, 0.001286831, 0.001283786, 0.001276838, 0.001272021, 0.001267212, 0.001260293, 0.001259416, 0.001252513, 0.001247736, 0.001242968, 0.001237888, 0.001233457, 0.001226597, 0.001223664, 0.001218938, 0.001212101, 0.001207388, 0.001202681, 0.001197659,
	0.001192959, 0.00118646, 0.001181438, 0.001178862, 0.001172053, 0.001169166, 0.00116449, 0.001159228, 0.001156347, 0.001149877, 0.00114489, 0.001138432, 0.001135578, 0.001130933, 0.001124174, 0.001121662, 0.001116715, 0.001112096, 0.001105685, 0.001100759, 0.001094361, 0.001091567, 0.001086981, 0.001082402, 0.001077509, 0.001072943, 0.001066264, 0.001061711, 0.001056843, 0.001052304, 0.001045651, 0.001040803,
	0.001034163, 0.00102965, 0.001023023, 0.001020321, 0.001015506, 0.001011018, 0.001004417, 0.000999621, 0.000993033, 0.00098825, 0.000983795, 0.000975107, 0.000972463, 0.000967705, 0.000963276, 0.000954613, 0.000949875, 0.000945464, 0.000940739, 0.000932102, 0.000929509, 0.000923004, 0.000918304, 0.000911812, 0.000907124, 0.000900645, 0.00089597, 0.000891301, 0.00088484, 0.000880184, 0.000875535, 0.000869093,
	0.000866575, 0.000858026, 0.000853401, 0.000848782, 0.00084417, 0.000837765, 0.000829247, 0.000826773, 0.000820387, 0.000817604, 0.00081123, 0.000804862, 0.000800299, 0.000793623, 0.000789393, 0.000782729, 0.00077819, 0.000771859, 0.000765534, 0.000763134, 0.0007565, 0.000752313, 0.000745691, 0.000741195, 0.000736541, 0.000731893, 0.00072725, 0.000722613, 0.000717982, 0.000713356, 0.000708735, 0.00070412, 0.00069951, 0.000694906, 0.000689385, 0.000684791, 0.000680203, 0.000675621, 0.000671044, 0.000667394, ])

# IMPORTANT: I specify that contract lengths may be only 20, 30, 40, 50, ..., 120 years.
# The code then chooses the most profitable crop option and contract length (20, 30, ..., or 120 years).
LENGTHS = np.arange(20, 121, 10) # Contract lengths: 20, 30, ..., 120 years.
T_MAX = int(LENGTHS[-1])
N_L = len(LENGTHS)
T_ARR = np.arange(T_MAX + 1, dtype=float)
WPT_MAT = np.zeros((N_L, T_MAX + 1))
for _i, _T in enumerate(LENGTHS): WPT_MAT[_i, :_T+1] = W_Carbon_T[_T::-1]
DISC_ARR = (1.0 - (1.0 + DISCOUNT_RATE) ** (-LENGTHS)) / DISCOUNT_RATE # Annuity factors at r=0.03 used for contract-length selection.
COMPOUND_ARR = (1.0 + DISCOUNT_RATE) ** LENGTHS # Compound factors at r=0.03 used for contract-length selection.

# Multi-rate bid evaluation. Contract length is fixed by the r=0.03 selection above;
# bids are then re-evaluated at these four rates so downstream code can apply any rate.
RATES = np.array([0.00, 0.015, 0.03, 0.06])
DISC_ARR_MULTI = np.where(RATES[:, None] == 0.0, LENGTHS[None, :].astype(float), (1.0 - (1.0 + RATES[:, None])**(-LENGTHS[None, :])) / RATES[:, None])  # (4, N_L)
COMPOUND_ARR_MULTI = (1.0 + RATES[:, None])**LENGTHS[None, :]  # (4, N_L)
TS_ARR_BY_T   = {int(T): np.arange(1, T + 1, dtype=float) for T in LENGTHS} # Pre-built year arrays for year-table output (year 1..T).
YEAR_ARR_BY_T   = {int(T): np.arange(T, dtype=np.int32) for T in LENGTHS}
WPT_MAT_F32     = WPT_MAT.astype(np.float32)     # float32 for SGEMM (~2x faster than DGEMM).
T_ARR_F32       = T_ARR.astype(np.float32)
TS_ARR_BY_T_F32 = {T: arr.astype(np.float32) for T, arr in TS_ARR_BY_T.items()}

def csv_path_for_length(output_dir: Path, T: int) -> Path:
	return output_dir / f"{UNDISCOUNTED_CSV_PREFIX}_{T:03d}.csv"

def initialize_csv_writers(output_dir: Path) -> tuple[dict[int, csv.writer], dict[int, object]]:
	# Open one CSV file per contract length and write the header row.
	# Returns (writers, handles) dicts keyed by contract length (int).
	output_dir.mkdir(parents=True, exist_ok=True)
	writers: dict[int, csv.writer] = {}
	handles: dict[int, object] = {}
	for T in LENGTHS.astype(int):
		fh = open(csv_path_for_length(output_dir, T), "w", newline="", encoding="utf-8")
		w = csv.writer(fh)
		w.writerow(["pixel_id", "option", "best_contract_length", "bid_r000", "bid_r015", "bid_r030", "bid_r060", "area_ha", "crop_va_USD_per_ha_per_year"] + [f"year{y}" for y in range(1, T + 1)])
		writers[T] = w
		handles[T] = fh
	return writers, handles

# Process one chunk of pixels for a country; called once per CHUNK_SIZE-row batch by process_country.
def process_chunk(iso: str, all_rows_for_one_country: dict[str, np.ndarray], csv_writers: dict[int, csv.writer]) -> None:
	N = len(all_rows_for_one_country["id"])

	# Data cleaning: ensure required columns exist with sensible defaults.
	for col in ["griscom", "brancalion", "bastin", "walker", "nr_buffer", "pl_buffer"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.zeros(N)
		else: all_rows_for_one_country[col] = np.where(np.isnan(all_rows_for_one_country[col]), 0.0, all_rows_for_one_country[col])
	for col in ["biomes", "nr_A", "type"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.full(N, np.nan)
	for col in ["nr_cost", "ep_cost", "np_cost", "crop_va"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.zeros(N)
	if "fao_ecoz" not in all_rows_for_one_country: all_rows_for_one_country["fao_ecoz"] = np.full(N, np.nan)

	# Drop deserts/xeric (biomes=13) and mangroves (biomes=14); drop missing nr_A and type.
	all_rows_for_one_country = {k: v[(all_rows_for_one_country["biomes"] != 13) & (all_rows_for_one_country["biomes"] != 14) & ~np.isnan(all_rows_for_one_country["nr_A"]) & ~np.isnan(all_rows_for_one_country["type"])] for k, v in all_rows_for_one_country.items()}
	N = len(all_rows_for_one_country["id"])

	if RUN_ONLY_ONE_PIXEL:
		all_rows_for_one_country = {k: v[all_rows_for_one_country["id"] == float(TARGET_PIXEL_ID)] for k, v in all_rows_for_one_country.items()}
		N = len(all_rows_for_one_country["id"])
	if N == 0: return

	# Convert 2011 establishment costs to 2020 USD. JFR: Note that the Busch et al code does not convert crop_va to 2020 USD, perhaps a mistake.
	for c in ["nr_cost", "ep_cost", "np_cost"]: all_rows_for_one_country[c] = all_rows_for_one_country[c] * 1.1577

	# Truncate negative A and k values at zero before growth calculations. JFR: a negative k implies growth without bound. Negative A implies growth toward a negative value.
	for col in CLAMP_COLS:
		if col in all_rows_for_one_country: all_rows_for_one_country[col][all_rows_for_one_country[col] < 0] = 0.0

	# Plantation genus mapping. Speed-up: numpy lookup replaces Python dict-loop per pixel.
	genus_arr = _GENUS_LOOKUP[all_rows_for_one_country["type"].astype(int)]
	all_rows_for_one_country["genus"] = genus_arr
	all_rows_for_one_country["genus_A"] = np.full(N, np.nan)
	all_rows_for_one_country["genus_k"] = np.full(N, np.nan)
	for g in GENUS_ORDER:
		mg = genus_arr == g
		if np.any(mg):
			all_rows_for_one_country["genus_A"][mg] = all_rows_for_one_country[f"{g}_A"][mg]
			all_rows_for_one_country["genus_k"][mg] = all_rows_for_one_country[f"{g}_k"][mg]

	# Convert area m² → ha.
	all_rows_for_one_country["area_ha"] = all_rows_for_one_country["area_m2"] / 10000.0

	# Root-shoot ratios (IPCC 2019 V4 Ch4 Table 4.4).
	all_rows_for_one_country["nr_rootshoot"] = np.full(N, 0.26)
	all_rows_for_one_country["pl_rootshoot"] = np.full(N, 0.26)
	continent = get_continent(iso)
	is_brde_nede = np.isin(genus_arr, ["brde", "nede"])
	is_pinu_cunn_brev_neev = np.isin(genus_arr, ["pinu", "cunn", "brev", "neev"])

	for eco, value in NR_ROOTSHOOT.get(continent, {}).items():
		all_rows_for_one_country["nr_rootshoot"][all_rows_for_one_country["fao_ecoz"] == eco] = value
	for eco, value in PL_ROOTSHOOT.get(continent, {}).items():
		all_rows_for_one_country["pl_rootshoot"][all_rows_for_one_country["fao_ecoz"] == eco] = value

	if continent == "AMER":
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.466
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.337
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.237
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.203
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.237
	elif continent == "ASIA":
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.225
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.243
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_brde_nede] = 0.225
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.243
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.307
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.224
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_brde_nede] = 0.307
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.224

	# Country-level scalars stored as full arrays.
	all_rows_for_one_country["wood_storage_share"] = np.full(N, mapped_value(WOOD_PRODUCT_STORAGE_MAP, iso))
	all_rows_for_one_country["p"] = np.full(N, mapped_value(WOOD_PRODUCT_REVENUE_MAP, iso))
	all_rows_for_one_country["exotic"] = np.full(N, mapped_value(EXOTIC_SHARE_MAP, iso))
	all_rows_for_one_country["native"] = 1.0 - all_rows_for_one_country["exotic"]
	all_rows_for_one_country["nr_npv_estcost_USD_per_ha"] = all_rows_for_one_country["nr_cost"].copy()
	
	# 2. Calculations. -------------------------------------------------------------------
	# 2.1 Natural regeneration calculations.
	nr_k = all_rows_for_one_country.get("nr_k", np.zeros(N))
	nr_A = all_rows_for_one_country["nr_A"]
	nr_rootshoot = all_rows_for_one_country["nr_rootshoot"]

	# LENGTHS, T_ARR, WPT_MAT, DISC_ARR are module-level constants computed once at startup.
	nr_scale = 2*nr_A*nr_k*(AGB_C_POOL + BGB_C_POOL*nr_rootshoot) # (N,)
	_e1_nr = np.exp(-nr_k.astype(np.float32)[:,None]*T_ARR_F32) # float32 exp; ~2x faster; use e**2 instead of second call.
	cs_nr = (nr_scale.astype(np.float32)[:,None]*(_e1_nr - _e1_nr**2) + np.float32(SOIL_C_POOL*NATURAL_SOIL_C)) # (N, T_MAX+1) float32
	warming_arr = WPT_MAT_F32 @ cs_nr.T # float32 SGEMM; ~2x faster than float64 DGEMM
	bid_arr = all_rows_for_one_country["nr_cost"] + all_rows_for_one_country["crop_va"] * DISC_ARR[:, None] # (N_L, N)
	# Find the contract length with cheapest $/(cooling °C) for natural regeneration.
	score_arr = bid_arr / warming_arr # (N_L, N) — float32 warming_arr upcasts to float64
	np.nan_to_num(score_arr, nan=np.inf, copy=False) # NaN bid/warming → inf; never chosen as best
	nr_idx = np.argmin(score_arr, axis=0) # (N,) index into LENGTHS
	nr_best_contract_length = LENGTHS[nr_idx]
	best_option = np.full(N, "NR", dtype=object)
	best_length = nr_best_contract_length.astype(float)
	best_score = score_arr[nr_idx, np.arange(N)]
	best_bid = bid_arr[nr_idx, np.arange(N)]
	# Track per-pixel establishment cost and harvest carbon for multi-rate bid computation below.
	best_est_cost = all_rows_for_one_country["nr_cost"].copy()  # est cost at the chosen option
	best_harvest_at_T = np.zeros(N)  # A*(1-exp(-k*T))^2 at the chosen T; 0 for NR
	del _e1_nr, cs_nr, warming_arr, score_arr, bid_arr # Memory: free NR intermediates before plantation loop.

	#2.2 Plantation calculations.
	all_rows_for_one_country["pl_best_contract_length"] = np.full(N, np.nan)
	for g in GENUS_ORDER:
		mask_g = genus_arr == g
		if not np.any(mask_g): continue
		A_g = all_rows_for_one_country[f"{g}_A"][mask_g]
		k_g = all_rows_for_one_country[f"{g}_k"][mask_g]
		rs_g = all_rows_for_one_country["pl_rootshoot"][mask_g]
		Ng = int(np.sum(mask_g))
		# Speed-up: same matrix-multiply pattern as NR; cs_pl (Ng, T_max+1), warming_g (n_L, Ng).
		pl_scale = 2*A_g*k_g*(AGB_C_POOL + BGB_C_POOL*rs_g) # (Ng,)
		_e1_pl = np.exp(-k_g.astype(np.float32)[:,None]*T_ARR_F32) # float32 exp; ~2x faster; use e**2 instead of second call.
		cs_pl = (pl_scale.astype(np.float32)[:,None]*(_e1_pl - _e1_pl**2) + np.float32(SOIL_C_POOL*PLANTATION_SOIL_C)) # (Ng, T_MAX+1) float32
		warming_g = WPT_MAT_F32 @ cs_pl.T # float32 SGEMM
		if g == "cunn": est_cost = all_rows_for_one_country["np_cost"][mask_g] if iso == "CHN" else all_rows_for_one_country["ep_cost"][mask_g]
		elif g == "euca": est_cost = all_rows_for_one_country["ep_cost"][mask_g]
		else: est_cost = all_rows_for_one_country["exotic"][mask_g] * all_rows_for_one_country["ep_cost"][mask_g] + all_rows_for_one_country["native"][mask_g] * all_rows_for_one_country["np_cost"][mask_g]
		harv_disc = HARVEST_C_POOL * (1.0 - np.exp(-k_g[:,None] * LENGTHS)) ** 2 / COMPOUND_ARR # (Ng, N_L)
		bid_g = est_cost[:,None] + all_rows_for_one_country["crop_va"][mask_g][:,None] * DISC_ARR - A_g[:,None] * harv_disc # (Ng, N_L)
		score_g = bid_g.T / warming_g # (N_L, Ng)
		np.nan_to_num(score_g, nan=np.inf, copy=False)
		pl_idx = np.argmin(score_g, axis=0)
		pl_len = LENGTHS[pl_idx]
		all_rows_for_one_country["pl_best_contract_length"][mask_g] = pl_len
		gi = np.arange(Ng)
		pl_score = score_g[pl_idx, gi]
		pl_bid = bid_g[gi, pl_idx]
		better = pl_score < best_score[mask_g]
		if np.any(better):
			bidx = np.flatnonzero(mask_g)[better]
			best_option[bidx] = g
			best_length[bidx] = pl_len[better].astype(float)
			best_score[bidx]  = pl_score[better]
			best_bid[bidx]    = pl_bid[better]
			best_est_cost[bidx] = est_cost[better]
			best_harvest_at_T[bidx] = HARVEST_C_POOL * A_g[better] * (1.0 - np.exp(-k_g[better] * pl_len[better].astype(float)))**2

	# 3. Output ---------------------------------------------------------------------------------
	# Compute bids at all four discount rates for the chosen option and contract length.
	# Contract length was selected using r=0.03; these bids fix that length and vary only the rate,
	# so downstream scripts (SMDAMAGE) can apply any discount rate without re-optimising.
	li = np.array([int(np.searchsorted(LENGTHS, int(T))) for T in best_length])  # index into LENGTHS/DISC_ARR_MULTI
	crop_va = all_rows_for_one_country["crop_va"]
	# best_bids_multi[ri, n] = est_cost[n] + crop_va[n]*annuity(r_i, T_n) - harvest_at_T[n] / (1+r_i)^T_n
	best_bids_multi = best_est_cost[None, :] + crop_va[None, :] * DISC_ARR_MULTI[:, li] - best_harvest_at_T[None, :] / COMPOUND_ARR_MULTI[:, li]  # (4, N)

	# Memory: drop columns not needed for CSV output before the valid-mask filter.
	for _k in list(all_rows_for_one_country):
		if _k not in KEEP_FOR_OUTPUT: all_rows_for_one_country.pop(_k)
	# Drop pixels where no valid option was found (best_score = inf means all bids were NaN).
	valid = np.isfinite(best_score)
	if not np.all(valid):
		best_option = best_option[valid]; best_length = best_length[valid]
		best_score = best_score[valid]; best_bid = best_bid[valid]
		best_bids_multi = best_bids_multi[:, valid]
		for key in list(all_rows_for_one_country.keys()): all_rows_for_one_country[key] = all_rows_for_one_country[key][valid]
		N = int(valid.sum())
	if N == 0: return

	ids = all_rows_for_one_country["id"].astype(np.int64)
	nr_A_f = all_rows_for_one_country["nr_A"]
	nr_k_f = all_rows_for_one_country.get("nr_k", np.zeros(N))
	nr_rs_f = all_rows_for_one_country["nr_rootshoot"]
	area_ha_f = all_rows_for_one_country["area_ha"]
	crop_va_f = all_rows_for_one_country["crop_va"]
	for opt in set(best_option.tolist()):
		mo = best_option == opt
		if opt == "NR": Av, kv, rsv, soil = nr_A_f[mo], nr_k_f[mo], nr_rs_f[mo], SOIL_C_POOL*NATURAL_SOIL_C
		else:
			Av = all_rows_for_one_country[f"{opt}_A"][mo]
			kv = all_rows_for_one_country[f"{opt}_k"][mo]
			rsv = all_rows_for_one_country["pl_rootshoot"][mo]
			soil = SOIL_C_POOL*PLANTATION_SOIL_C
		gidx = np.flatnonzero(mo)
		blens = best_length[mo].astype(int)
		for T in np.unique(blens):
			sub = blens == T
			As, ks, rss = Av[sub].astype(np.float32), kv[sub].astype(np.float32), rsv[sub].astype(np.float32)
			_e1_cs = np.exp(-ks[:, None]*TS_ARR_BY_T_F32[T])
			cs = (2*As[:, None]*ks[:, None]*(np.float32(AGB_C_POOL) + np.float32(BGB_C_POOL)*rss[:, None]) * (_e1_cs - _e1_cs**2) + np.float32(soil))
			if opt != "NR": cs[:, -1] -= np.float32(HARVEST_C_POOL) * As * (1.0 - np.exp(-ks * np.float32(T)))**2
			sidx = gidx[sub]  # global pixel indices for this (opt, T) group
			pids = ids[sidx]
			writer = csv_writers[T]
			bids = best_bids_multi[:, sidx]  # (4, n_sub)
			areas = area_ha_f[sidx]
			cvas = crop_va_f[sidx]
			for j in range(len(sidx)):
				writer.writerow([int(pids[j]), opt, T,
					float(bids[0, j]), float(bids[1, j]), float(bids[2, j]), float(bids[3, j]),
					float(areas[j]), float(cvas[j])] + cs[j].tolist())

# Execute one country pipeline from input .dta to CSV output, streaming in CHUNK_SIZE-row batches.
# pixel_id_start: 1-based global pixel counter accumulated across ALL countries.
# Returns the updated pixel_id_start after this country's rows are processed.
# pixel_id is a global counter, not restarting per country, ensuring unique IDs across the full dataset.
def process_country(iso: str, dta_dir: Path, macc_dir: Path, csv_writers: dict[int, csv.writer], pixel_id_start: int = 0) -> int:
	filepath = next((c for c in [dta_dir / iso, dta_dir / f"{iso}.dta", dta_dir / f"maps_{iso}.dta"] if c.is_file()), None)
	if filepath is None: print(f"[SKIP] {iso}: .dta file not found.", flush=True); return pixel_id_start
	pixel_id_offset = pixel_id_start
	for df in pd.read_stata(str(filepath), chunksize=CHUNK_SIZE, convert_dates=False, convert_categoricals=False):
		d = {col: np.array(df[col], dtype=float) for col in df.columns}
		d = {col: arr for col, arr in d.items() if col in KEEP_COLS}
		n = len(df)
		# pixel_id continues from the global offset so IDs are unique across all countries.
		d["id"] = np.arange(pixel_id_offset + 1, pixel_id_offset + n + 1, dtype=float)
		pixel_id_offset += n
		process_chunk(iso, d, csv_writers)
	print(f"[OK] {iso} {f'pixel {TARGET_PIXEL_ID}' if RUN_ONLY_ONE_PIXEL else 'all pixels'}", flush=True)
	return pixel_id_offset

# --- Run all countries in order of increasing .dta file size. -------------------
# Set RESUME_AFTER_ISO to skip already-processed countries.
# If RESUME_AFTER_ISO is "", all countries are processed from the start.
# NOTE: If resuming, pixel IDs will be wrong unless you know the correct global offset
# for the first country you want to process. Only use "" for a full fresh run.
RESUME_AFTER_ISO = "" 
if RESUME_AFTER_ISO:
	cutoff_src = next((c for c in [DTA_DIR / RESUME_AFTER_ISO, DTA_DIR / f"{RESUME_AFTER_ISO}.dta"] if c.is_file()), None)
	if cutoff_src is None: raise FileNotFoundError(f"{RESUME_AFTER_ISO}.dta not found in {DTA_DIR}")
	cutoff_size = cutoff_src.stat().st_size
	requested_isos = [p.stem.upper() for p in sorted(DTA_DIR.glob("*.dta"), key=lambda p: p.stat().st_size) if p.stat().st_size > cutoff_size]
else:
	requested_isos = [p.stem.upper() for p in sorted(DTA_DIR.glob("*.dta"), key=lambda p: p.stat().st_size)]
print(f"{len(requested_isos)} countries to process. Starting at {time.strftime('%Y-%m-%d %H:%M:%S')}", flush=True)

csv_writers, csv_handles = initialize_csv_writers(OUTPUT_CSV_DIR)
global_pixel_offset = 0
for iso in requested_isos:
	size_mb = next((p.stat().st_size / 1e6 for p in DTA_DIR.glob(f"{iso}*.dta") if p.is_file()), 0)
	t0 = time.perf_counter()
	try: global_pixel_offset = process_country(iso=iso, dta_dir=DTA_DIR, macc_dir=OUTPUT_CSV_DIR, csv_writers=csv_writers, pixel_id_start=global_pixel_offset)
	except Exception as exc:
		print(f"[FAIL] {iso}: {exc}", flush=True)
		continue
	elapsed = time.perf_counter() - t0
	print(f"  {elapsed:.1f}s / {size_mb:.1f} MB = {elapsed/size_mb:.2f} s/MB", flush=True)
for fh in csv_handles.values(): fh.close()
print(f"End: {time.strftime('%Y-%m-%d %H:%M:%S')}. Total pixels: {global_pixel_offset:,}.", flush=True)
