# 1a_import_Busch2024_to_SMDAMAGE.py — Written by JFR and CoPilot (mostly Claude), 2026-07-14.
# Purpose: Busch2024_to_SMDAMAGE.sqlite is the data bridge between the Busch 2024 paper ".dta" files and SMDAMAGE.
# Each pixel in each .dta file is treated as a bidder. Each bidder chooses a most profitable crop
# (natural regeneration or some plantation crop), the associated carbon removal schedule and a bid price to the SMDAMAGE auction.
# But 58 million bidders is too big for SMDAMAGE, so I use a k-means to cluster similar bidders into groups.
# Later in the workflow, SMDAMAGE project file create_database.py reads Busch2024_to_SMDAMAGE.sqlite
# and loads forestry bidders, one per group, into the SMDAMAGE auction.

# Origin: I adapted this code from "1. Model loop all data corrected.do", the Stata pipeline published by Busch et al,
# "Cost-effectiveness of natural forest regeneration and plantations for climate mitigation" (2024).
# That Stata script reads per-country .dta input files, applies biome and geographic filters,
# computes Chapman-Richards carbon growth curves under natural regeneration and plantation scenarios,
# applies IPCC root-to-shoot ratios and FAO ecozone rules, evaluates cost-effectiveness per pixel
# in $/tCO2, and selects the least-cost reforestation option for each pixel.

# This version replaces the Busch et al harvest-year selection with a bid_score approach.
# For each pixel, the winning option and contract length minimise bid / warming ($/°C cooling),
# where bid = establishment_cost + discounted_opportunity_cost (- discounted_harvest_NPV for plantations)
# and warming = convolution of annual carbon sequestration with the Hector climate impulse response.
 
# Input:
#   Input/*.dta published by Busch et al as the replication dataset for the 2024 paper.
#   Not generated by any script in this repo; download from the paper’s data repository.
#   Each .dta file contains pixel information on one country. One row per pixel with
#   Chapman-Richards growth parameters (A, k) for natural regeneration and each plantation
#   genus, establishment costs, crop opportunity value, area, biome, FAO ecozone, and
#   geographic screen variables (griscom, brancalion, bastin, walker).
#
# Output: Output/Databases/Busch2024_to_SMDAMAGE.sqlite, two tables:
#   Undiscounted_dta_output, one row per pixel:
#     country, pixel_id, option (NR or plantation genus), best_contract_length,
#     bid (USD/ha at best_contract_length), bid_score (int, bid/warming at best_contract_length),
#     area_ha, crop_va_USD_per_ha_per_year.
#   tC_per_h_per_year, one row per pixel per year (year 0 … best_contract_length-1):
#     country, pixel_id, year, tC_per_ha_per_year.
#
# Downstream pipeline (later scripts add further tables to the same SQLite file):
#   2_k_means_carbon_removal.py — clusters pixels on their carbon profiles within each contract
#     length; writes cluster centre schedules (carbon_removal_schedules) and assigns each pixel
#     a cluster_index (added as a column on Undiscounted_dta_output).
#   3_import_k_means_csv_to_sqlite.py — loads k-means CSV results into the database.
#   4_move_Busch_data_to_SMDAMAGE.py — computes per-pixel NPV bid costs and builds area-share
#     bid-step supply curves (forestry_bid_curves), one curve per (contract_length, cluster_index).

from __future__ import annotations
import argparse
import csv
import functools
import time
from pathlib import Path
import sqlite3
import numpy as np
import pyreadstat

SMDAMAGE_DB_FILE = "Busch2024_to_SMDAMAGE.sqlite"
SMDAMAGE_DATA_DB  = Path(r"C:\Users\johnr\Documents\Work documents\2 Research\Global warming\Numerical Simulation\SMDAMAGE revenue neutral\SMDAMAGE for Git\Data\smdamage_data.db")
SMDAMAGE_PIXEL_TABLE = "Undiscounted_dta_output"
SMDAMAGE_YEAR_TABLE = "tC_per_h_per_year"
TARGET_PIXEL_ID = 5119
RUN_ONLY_ONE_PIXEL = False
GENUS_ORDER = ["pinu", "cunn", "euca", "brde", "brev", "nede", "neev"]
GENUS_BY_TYPE = {1: "neev", 2: "brev", 3: "brde", 4: "neev", 5: "cunn", 6: "euca", 7: "nede", 8: "neev", 9: "pinu", 10: "brde", 11: "neev", 12: "brde", 13: "brev", 14: "brde", 15: "neev"}
TIME_HORIZON_YEARS = 120  # Must cover the full contract-length range (lengths goes to 115).
DISCOUNT_RATE = 0.03      # Used for bid discounting; 3% real rate.
AUSTMANN_F = 1
NATURAL_SOIL_C = 0.415107735
PLANTATION_SOIL_C = 0.092749069
AGB_C_POOL = 1
BGB_C_POOL = 1
SOIL_C_POOL = 1
HARVEST_C_POOL = 1
SMALL_DTA_COUNT = 50
SKIP_SQLITE_EXPORT = False
HARVEST_YEAR_BUCKETS_CSV = Path(__file__).resolve().parent.parent / "Output" / "choose_harvest_years_mapping.csv"
RESUME_AFTER_ISO = "KAZ"

AFRI = {"DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "COG", "CIV", "COD", "DJI", "EGY", "GNQ",
	"ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "LBY", "MDG", "MWI", "MDV", "MLI", "MRT", "MUS",
	"MAR", "MOZ", "NAM", "NER", "NGA", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TZA", "TGO", "TUN", "UGA",
	"ESH", "ZMB", "ZWE"}
AMER = {"ATG", "ARG", "BRB", "BLZ", "BOL", "BRA", "CHL", "COL", "CRI", "CUB", "DMA", "DOM", "ECU", "SLV", "GUF", "GRD", "GTM",
	"GUY", "HTI", "HND", "JAM", "MEX", "NIC", "PAN", "PRY", "PER", "KNA", "LCA", "VCT", "SUR", "TTO", "URY", "VEN"}
ASIA = {"AFG", "BGD", "BTN", "KHM", "CHN", "COK", "PRK", "FJI", "IND", "IDN", "IRN", "IRQ", "JOR", "KAZ", "KIR", "KGZ", "LAO",
	"LBN", "MYS", "MHL", "FSM", "MNG", "MMR", "NRU", "NPL", "OMN", "PAK", "PLW", "PSE", "PNG", "PHL", "WSM", "SLB", "LKA", "SYR",
	"TJK", "THA", "TLS", "TKL", "TON", "TKM", "TUV", "UZB", "VUT", "VNM", "YEM", "ARM", "AZE", "GEO", "TUR"}

NR_ROOTSHOOT_RULES = {(11, "AFRI"): 0.825, (11, "AMER"): 0.221, (11, "ASIA"): 0.207, (12, "AFRI"): 0.232, (12, "AMER"): 0.2845, (12, "ASIA"): 0.323,
	(13, "AFRI"): 0.332, (13, "AMER"): 0.334, (13, "ASIA"): 0.440, (16, "AMER"): 0.348, (16, "ASIA"): 0.322, (21, "AFRI"): 0.232, (21, "AMER"): 0.175,
	(21, "ASIA"): 0.230, (22, "AMER"): 0.336, (22, "ASIA"): 0.440, (23, "AMER"): 1.338, (23, "ASIA"): 1.338}
PL_ROOTSHOOT_RULES = {(11, "AMER"): 0.170, (11, "ASIA"): 0.325, (16, "AMER"): 2.158, (23, "ASIA"): 2.158}

WOOD_PRODUCT_STORAGE_MAP = {0.188: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "MEX", "NIC", "PAN", "SLV", "TTO", "VCT"},
	0.268: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PER", "PRY", "SUR", "URY", "VEN"},
	0.355: {"AFG", "ARM", "AZE", "BGD", "BTN", "CHN", "GEO", "IDN", "IND", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "KHM", "LAO", "LBN", "LKA", "MMR", "MNG", "MYS", "NPL", "OMN", "PAK", "PHL", "PNG", "PRK", "PSE", "SYR", "THA", "TJK", "TKM", "TLS", "TUR", "UZB", "VNM", "YEM"},
	0.392: {"AGO", "BDI", "BEN", "BFA", "BWA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "DZA", "EGY", "ERI", "ESH", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "LBY", "LSO", "MAR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NAM", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SWZ", "SYC", "TCD", "TGO", "TUN", "TZA", "UGA", "ZAF", "ZMB", "ZWE"},
	0.415: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}}
WOOD_PRODUCT_REVENUE_MAP = {52.65: {"ATG", "BLZ", "BRB", "CRI", "CUB", "DMA", "DOM", "GRD", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "NIC", "PAN", "SLV", "TTO", "VCT"},
	59.73: {"MEX"}, 61.04: {"BOL", "BRA", "COL", "ECU", "GUF", "GUY", "PER", "SUR", "VEN"}, 67.76: {"BGD", "IDN", "KHM", "LAO", "LKA", "MMR", "MYS", "OMN", "PHL", "PNG", "THA", "TLS", "VNM", "YEM"},
	69.26: {"PRY"}, 71.24: {"AGO", "BDI", "BEN", "BFA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "ERI", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "MDG", "MDV", "MLI", "MOZ", "MRT", "MUS", "MWI", "NER", "NGA", "RWA", "SDN", "SEN", "SLE", "SOM", "SSD", "STP", "SYC", "TCD", "TGO", "TZA", "UGA", "ZMB", "ZWE"},
	76.08: {"COK", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "SLB", "TKL", "TON", "TUV", "VUT", "WSM"}, 76.88: {"IND"}, 80.003: {"ARG", "CHL", "URY"}, 80.83: {"BWA", "NAM"},
	88.84: {"AFG", "ARM", "AZE", "BTN", "CHN", "GEO", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "MNG", "NPL", "PAK", "PRK", "PSE", "SYR", "TJK", "TKM", "TUR", "UZB"},
	93.40: {"DZA", "EGY", "ESH", "LBY", "LSO", "MAR", "SWZ", "TUN", "ZAF"}}
EXOTIC_SHARE_MAP = {0.74: {"AGO", "BWA", "COM", "DJI", "ERI", "SWZ", "ETH", "KEN", "LSO", "MDG", "MWI", "MDV", "MUS", "MOZ", "NAM", "SYC", "SOM", "ZAF", "SSD", "SDN", "TZA", "UGA", "ZMB", "ZWE", "BEN", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COG", "CIV", "COD", "GNQ", "GAB", "GMB", "GHA", "GIN", "GNB", "LBR", "MLI", "MRT", "NER", "NGA", "RWA", "STP", "SEN", "SLE", "TGO"},
	0.50: {"DZA", "EGY", "LBY", "MAR", "TUN", "ESH"}, 0.31: {"CHN", "PRK", "MNG"}, 0.40: {"BGD", "BTN", "KHM", "IND", "IDN", "LAO", "MYS", "MMR", "NPL", "PAK", "PHL", "LKA", "THA", "TLS", "VNM"},
	0.05: {"AFG", "IRN", "IRQ", "JOR", "KAZ", "KGZ", "LBN", "OMN", "PSE", "SYR", "TJK", "TKM", "UZB", "YEM", "ARM", "AZE", "GEO", "TUR"},
	0.78: {"COK", "FJI", "KIR", "MHL", "FSM", "NRU", "PLW", "PNG", "WSM", "SLB", "TKL", "TON", "TUV", "VUT"}, 0.32: {"ATG", "BRB", "CUB", "DMA", "DOM", "GRD", "HTI", "KNA", "LCA", "VCT", "TTO"},
	0.18: {"BLZ", "CRI", "SLV", "GTM", "HND", "JAM", "MEX", "NIC", "PAN"}, 0.97: {"ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"}}

def get_continent(iso: str) -> str: return "AFRI" if iso in AFRI else "AMER" if iso in AMER else "ASIA" if iso in ASIA else ""
def mapped_value(mapping: dict[float, set[str]], iso: str, default: float = 0.0) -> float: return next((value for value, isos in mapping.items() if iso in isos), default)
def iter_input_isos(dta_dir: Path) -> list[str]: return sorted(path.stem.upper() for path in dta_dir.glob("*.dta") if path.is_file())
def iter_smallest_input_isos(dta_dir: Path, count: int) -> list[str]: return [path.stem.upper() for path in sorted((path for path in dta_dir.glob("*.dta") if path.is_file()), key=lambda path: (path.stat().st_size, path.stem.upper()))[:count]]

# Delete. Won't be reading harvest_year_buckets.csv
# @functools.lru_cache(maxsize=1)
# def load_harvest_year_buckets(csv_path: Path = HARVEST_YEAR_BUCKETS_CSV) -> dict[int, int]:
# 	if not csv_path.exists(): raise FileNotFoundError(f"Run 0_choose_harvest_years.py first: {csv_path}")
# 	buckets: dict[int, int] = {}
# 	with open(csv_path, newline='') as f:
# 		for row in csv.DictReader(f): buckets[int(row["original_harvest_year"])] = int(row["chosen_harvest_year"])
# 	floor_year = min(buckets.values())
# 	for year in range(3, min(buckets)): buckets[year] = floor_year
# 	return buckets

@functools.lru_cache(maxsize=1)
def get_carbon_wpt() -> np.ndarray:
	"""Impulse response: warming (thousandths °C per MtC) for 296 years. Cached."""
	conn = sqlite3.connect(SMDAMAGE_DATA_DB)
	row  = conn.execute("SELECT * FROM warming_factors WHERE hector_name = 'ffi_emissions'").fetchone()
	conn.close()
	emission_factor = row[2]  # usually 1.0
	# row[4:] are year_001..year_296 in degrees/GtC; *1000 → thousandths/GtC; /1000 → thousandths/MtC
	return np.array([float(row[4 + t]) / emission_factor for t in range(296)])

# Delete.
# def calculate_harvest_year(k: np.ndarray, time_horizon_years: int, discount_rate: float) -> np.ndarray:
# 	harvest_year = np.full(len(k), float(time_horizon_years + 1))
# 	for year in range(3, time_horizon_years + 1):
# 		term2 = (1 - np.exp(-k * (year - 2))) ** 2
# 		with np.errstate(invalid='ignore', divide='ignore'):
# 			harvest_year = np.where(np.where(term2 == 0, np.nan, ((1 - np.exp(-k * (year - 1))) ** 2 - term2) / term2)
# 				> discount_rate / (1 - (1 + discount_rate) ** (-(year - 1))), float(year), harvest_year)
# 	buckets = load_harvest_year_buckets()
# 	max_yr = int(np.max(harvest_year)) if len(harvest_year) > 0 else time_horizon_years + 1
# 	lookup = np.arange(0, max_yr + 2, dtype=float)  # identity mapping by default
# 	for orig, chosen in buckets.items():
# 		if 0 <= orig <= max_yr + 1: lookup[orig] = float(chosen)
# 	return lookup[harvest_year.astype(int)]

def initialize_smdamage_database(output_dir: Path) -> None:
	output_dir.mkdir(parents=True, exist_ok=True)
	with sqlite3.connect(output_dir / SMDAMAGE_DB_FILE) as conn:
		conn.execute(f"DROP TABLE IF EXISTS {SMDAMAGE_PIXEL_TABLE}")
		conn.execute(f"DROP TABLE IF EXISTS {SMDAMAGE_YEAR_TABLE}")
		conn.execute(f"CREATE TABLE {SMDAMAGE_PIXEL_TABLE} (country TEXT NOT NULL, pixel_id INTEGER NOT NULL, option TEXT, best_contract_length INTEGER, bid REAL, bid_score INTEGER, area_ha REAL, crop_va_USD_per_ha_per_year REAL)")
		conn.execute(f"CREATE TABLE {SMDAMAGE_YEAR_TABLE} (country TEXT NOT NULL, pixel_id INTEGER NOT NULL, year INTEGER NOT NULL, tC_per_ha_per_year REAL)")

# Consider deleting this function.
# def clear_smdamage_country(conn: sqlite3.Connection, country: str) -> None:
# 	conn.execute(f"DELETE FROM {SMDAMAGE_PIXEL_TABLE} WHERE country = ?", (country,))
# 	conn.execute(f"DELETE FROM {SMDAMAGE_YEAR_TABLE} WHERE country = ?", (country,))

# Execute one country pipeline from input .dta to SMDAMAGE exports.
def process_country(iso: str, dta_dir: Path, macc_dir: Path) -> dict[str, int]:

	# 1. Import of data & data cleaning. -------------------------------------------------------------------
	# Read .dta file via pyreadstat; output_format='dict' returns OrderedDict of Python lists.
	# np.array(lst, dtype=float) converts None (Stata missing) to NaN.
	all_rows_for_one_country: dict[str, np.ndarray] = {k: np.array(v, dtype=float) 
		for k, v in pyreadstat.read_dta(str(next((c for c in [dta_dir / iso, dta_dir / f"{iso}.dta", dta_dir / f"maps_{iso}.dta"] if c.is_file()), None)),
		output_format='dict', disable_datetime_conversion=True)[0].items()}
	N0 = len(next(iter(all_rows_for_one_country.values())))

	# Some country files have an integer row identifier pxl_id, but not all. This code ignores pxl_id and generates its own id.
	all_rows_for_one_country["id"] = np.arange(1, N0 + 1, dtype=float)

	# Data cleaning: ensure required columns exist with sensible defaults.
	for col in ["griscom", "brancalion", "bastin", "walker", "nr_buffer", "pl_buffer"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.zeros(N0)
		else: all_rows_for_one_country[col] = np.where(np.isnan(all_rows_for_one_country[col]), 0.0, all_rows_for_one_country[col])
	for col in ["biomes", "nr_A", "type"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.full(N0, np.nan)
	for col in ["nr_cost", "ep_cost", "np_cost", "crop_va"]:
		if col not in all_rows_for_one_country: all_rows_for_one_country[col] = np.zeros(N0)
	if "fao_ecoz" not in all_rows_for_one_country: all_rows_for_one_country["fao_ecoz"] = np.full(N0, np.nan)

	# Drop deserts/xeric (biomes=13) and mangroves (biomes=14); drop missing nr_A and type.
	all_rows_for_one_country = {k: v[(all_rows_for_one_country["biomes"] != 13) & (all_rows_for_one_country["biomes"] != 14) & ~np.isnan(all_rows_for_one_country["nr_A"]) & ~np.isnan(all_rows_for_one_country["type"])] for k, v in all_rows_for_one_country.items()}
	N = len(all_rows_for_one_country["id"])
	print("Number valid pixels is ", N)

	if RUN_ONLY_ONE_PIXEL:
		all_rows_for_one_country = {k: v[all_rows_for_one_country["id"] == float(TARGET_PIXEL_ID)] for k, v in all_rows_for_one_country.items()}
		N = len(all_rows_for_one_country["id"])
	# THIS DOESN'T LOOK RIGHT
	if N == 0: print(f"[SKIP] {iso}: no matching pixels.", flush=True); return {}

	# Convert 2011 establishment costs to 2020 USD. JFR: Note that the Busch et al code does not convert crop_va to 2020 USD, perhaps a mistake.
	for c in ["nr_cost", "ep_cost", "np_cost"]: all_rows_for_one_country[c] = all_rows_for_one_country[c] * 1.1577

	# Truncate negative A and k values at zero before growth calculations. JFR: a negative k implies growth without bound. Negative A implies growth toward a negative value.
	for col in ["nr_A", "nr_k"] + [f"{g}_{s}" for g in GENUS_ORDER for s in ["A", "k"]]:
		if col in all_rows_for_one_country: all_rows_for_one_country[col][all_rows_for_one_country[col] < 0] = 0.0

	# Plantation genus mapping.
	genus_arr = np.array([GENUS_BY_TYPE.get(t, "") for t in all_rows_for_one_country["type"].astype(int)], dtype=object)
	all_rows_for_one_country["genus"] = genus_arr
	all_rows_for_one_country["genus_A"] = np.full(N, np.nan)
	all_rows_for_one_country["genus_k"] = np.full(N, np.nan)
	for g in GENUS_ORDER:
		mg = genus_arr == g
		if np.any(mg):
			all_rows_for_one_country["genus_A"][mg] = all_rows_for_one_country[f"{g}_A"][mg]
			all_rows_for_one_country["genus_k"][mg] = all_rows_for_one_country[f"{g}_k"][mg]

	# Convert area m² → ha.
	all_rows_for_one_country["area_ha"] = all_rows_for_one_country["area_m2"] / 10000.0

	# Root-shoot ratios (IPCC 2019 V4 Ch4 Table 4.4).
	all_rows_for_one_country["nr_rootshoot"] = np.full(N, 0.26)
	all_rows_for_one_country["pl_rootshoot"] = np.full(N, 0.26)
	continent = get_continent(iso)
	is_brde_nede = np.isin(genus_arr, ["brde", "nede"])
	is_pinu_cunn_brev_neev = np.isin(genus_arr, ["pinu", "cunn", "brev", "neev"])

	for (eco, cont), value in NR_ROOTSHOOT_RULES.items():
		if cont == continent: all_rows_for_one_country["nr_rootshoot"][all_rows_for_one_country["fao_ecoz"] == eco] = value
	for (eco, cont), value in PL_ROOTSHOOT_RULES.items():
		if cont == continent: all_rows_for_one_country["pl_rootshoot"][all_rows_for_one_country["fao_ecoz"] == eco] = value

	if continent == "AMER":
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.466
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.337
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.237
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.203
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.237
	elif continent == "ASIA":
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.225
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.243
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_brde_nede] = 0.225
		all_rows_for_one_country["nr_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.243
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_brde_nede] = 0.307
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 31) & is_pinu_cunn_brev_neev] = 0.224
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_brde_nede] = 0.307
		all_rows_for_one_country["pl_rootshoot"][(all_rows_for_one_country["fao_ecoz"] == 32) & is_pinu_cunn_brev_neev] = 0.224

	# Country-level scalars stored as full arrays.
	all_rows_for_one_country["wood_storage_share"]      = np.full(N, mapped_value(WOOD_PRODUCT_STORAGE_MAP, iso))
	all_rows_for_one_country["p"]      = np.full(N, mapped_value(WOOD_PRODUCT_REVENUE_MAP, iso))
	all_rows_for_one_country["exotic"] = np.full(N, mapped_value(EXOTIC_SHARE_MAP, iso))
	all_rows_for_one_country["native"] = 1.0 - all_rows_for_one_country["exotic"]
	all_rows_for_one_country["nr_npv_estcost_USD_per_ha"] = all_rows_for_one_country["nr_cost"].copy()
	
	# 2. Calculations. -------------------------------------------------------------------
	# 2.1 Natural regeneration calculations.
	nr_k         = all_rows_for_one_country.get("nr_k", np.zeros(N))
	nr_A         = all_rows_for_one_country["nr_A"]
	nr_rootshoot = all_rows_for_one_country["nr_rootshoot"]
	years        = np.arange(200)[:, np.newaxis]   # (200,1) broadcasts over N pixels
	carbon_schedule = 2*nr_A*nr_k*(AGB_C_POOL + BGB_C_POOL*nr_rootshoot)*(np.exp(-nr_k*years) - np.exp(-2*nr_k*years)) + SOIL_C_POOL*NATURAL_SOIL_C
	carbon_wpt   = get_carbon_wpt() # Warming in year t from a megaton release of carbon in year 0.
	lengths      = np.arange(20, 120, 5)
	# Warming in year t from a mhectare planting in year 0.
	warming      = {T: (carbon_wpt[T::-1, np.newaxis] * carbon_schedule[:T+1]).sum(axis=0) for T in lengths}
	bid          = {T: all_rows_for_one_country["nr_cost"] + all_rows_for_one_country["crop_va"] * (1.0 - (1.0 + DISCOUNT_RATE) ** (-T)) / DISCOUNT_RATE for T in lengths}
	# Find the contract length with cheapest $/(cooling °C) for natural regeneration.
	len_idx     = {int(T): i for i, T in enumerate(lengths)}
	score_arr   = np.stack([bid[T] / warming[T] for T in lengths])  # (n_lengths, N)
	np.nan_to_num(score_arr, nan=np.inf, copy=False)  # NaN bid/warming → inf; never chosen as best
	nr_idx      = np.argmin(score_arr, axis=0)          # (N,) index into lengths
	nr_best_contract_length = lengths[nr_idx]
	best_option = np.full(N, "NR", dtype=object)
	best_length = nr_best_contract_length.astype(float)
	best_score  = score_arr[nr_idx, np.arange(N)]
	best_bid    = np.stack([bid[T] for T in lengths])[nr_idx, np.arange(N)]
	best_cs     = carbon_schedule.copy()  # (200, N); updated where plantation wins

	#2.2 Plantation calculations.
	all_rows_for_one_country["pl_best_contract_length"] = np.full(N, np.nan)
	for g in GENUS_ORDER:
		mask_g = genus_arr == g
		if not np.any(mask_g): continue
		A_g  = all_rows_for_one_country[f"{g}_A"][mask_g]
		k_g  = all_rows_for_one_country[f"{g}_k"][mask_g]
		rs_g = all_rows_for_one_country["pl_rootshoot"][mask_g]
		carbon_schedule_g = 2*A_g*k_g*(AGB_C_POOL + BGB_C_POOL*rs_g)*(np.exp(-k_g*years) - np.exp(-2*k_g*years)) + SOIL_C_POOL*PLANTATION_SOIL_C
		warming_g = {T: (carbon_wpt[T::-1, np.newaxis] * carbon_schedule_g[:T+1]).sum(axis=0) for T in lengths}
		if g == "cunn": est_cost = all_rows_for_one_country["np_cost"][mask_g] if iso == "CHN" else all_rows_for_one_country["ep_cost"][mask_g]
		elif g == "euca": est_cost = all_rows_for_one_country["ep_cost"][mask_g]
		else: est_cost = all_rows_for_one_country["exotic"][mask_g] * all_rows_for_one_country["ep_cost"][mask_g] + all_rows_for_one_country["native"][mask_g] * all_rows_for_one_country["np_cost"][mask_g]
		bid_g    = {T: est_cost + all_rows_for_one_country["crop_va"][mask_g] * (1.0 - (1.0 + DISCOUNT_RATE) ** (-T)) / DISCOUNT_RATE
			- A_g * (1.0 - np.exp(-k_g * T)) ** 2 / (1.0 + DISCOUNT_RATE) ** T for T in lengths}
		score_g  = np.stack([bid_g[T] / warming_g[T] for T in lengths])   # (n_lengths, Ng)
		np.nan_to_num(score_g, nan=np.inf, copy=False)
		pl_idx   = np.argmin(score_g, axis=0)
		pl_len   = lengths[pl_idx]
		all_rows_for_one_country["pl_best_contract_length"][mask_g] = pl_len
		gi       = np.arange(carbon_schedule_g.shape[1])
		pl_score = score_g[pl_idx, gi]
		pl_bid   = np.stack([bid_g[T] for T in lengths])[pl_idx, gi]
		better   = pl_score < best_score[mask_g]
		best_option[mask_g] = np.where(better, g, best_option[mask_g])
		best_length[mask_g] = np.where(better, pl_len.astype(float), best_length[mask_g])
		best_score[mask_g]  = np.where(better, pl_score, best_score[mask_g])
		best_bid[mask_g]    = np.where(better, pl_bid, best_bid[mask_g])
		best_cs[:, np.flatnonzero(mask_g)[better]] = carbon_schedule_g[:, better]

	# 3. Output ---------------------------------------------------------------------------------
	# Drop pixels where no valid option was found (best_score = inf means all bids were NaN).
	valid = np.isfinite(best_score)
	if not np.all(valid):
		# n_skip = int((~valid).sum())
		# print(f"  {iso}: {n_skip} pixel(s) with no valid option excluded.", flush=True)
		best_option = best_option[valid]; best_length = best_length[valid]
		best_score  = best_score[valid];  best_bid    = best_bid[valid]
		best_cs     = best_cs[:, valid]
		for key in list(all_rows_for_one_country.keys()): all_rows_for_one_country[key] = all_rows_for_one_country[key][valid]
		N = int(valid.sum())
	if N == 0: return {}
	macc_dir.mkdir(parents=True, exist_ok=True)
	if SKIP_SQLITE_EXPORT: print(f"[SKIP_SQLITE_EXPORT] {iso}", flush=True)
	else:
		with sqlite3.connect(macc_dir / SMDAMAGE_DB_FILE) as conn:
			conn.execute("PRAGMA synchronous = OFF")
			conn.execute("PRAGMA cache_size = -131072")
			ids = [int(x) for x in all_rows_for_one_country["id"]]
			conn.executemany(f"INSERT INTO {SMDAMAGE_PIXEL_TABLE} VALUES (?,?,?,?,?,?,?,?)",
				zip([iso]*N, ids, best_option.tolist(), best_length.astype(int).tolist(), best_bid.tolist(),
					best_score.astype(int).tolist(), all_rows_for_one_country["area_ha"].tolist(), all_rows_for_one_country["crop_va"].tolist()))
			conn.executemany(f"INSERT INTO {SMDAMAGE_YEAR_TABLE} VALUES (?,?,?,?)", ((iso, ids[i], t, float(best_cs[t, i])) for i in range(N) for t in range(int(best_length[i]))))
	print(f"[OK] {iso} {f'pixel {TARGET_PIXEL_ID}' if RUN_ONLY_ONE_PIXEL else 'all pixels'}", flush=True)
	return

# Iterate across requested ISO codes and run the country pipeline.
def main() -> None:
	parser = argparse.ArgumentParser(description="Pandas-free version of 1_import_Busch2024_to_SMDAMAGE.py")
	parser.add_argument("--dta-dir", type=Path, required=True, help="Directory containing per-country .dta input files")
	parser.add_argument("--macc-dir", type=Path, required=True, help="Directory to write output SQLite database")
	parser.add_argument("--iso", nargs="*", help="Optional ISO code filter.")
	parser.add_argument("--smallest-n", type=int, help="Optional count of smallest .dta files to process.")
	args = parser.parse_args()
	requested_isos = sorted(iso.upper() for iso in args.iso) if args.iso else iter_smallest_input_isos(args.dta_dir, args.smallest_n) if args.smallest_n else iter_input_isos(args.dta_dir)
	initialize_smdamage_database(args.macc_dir)
	for iso in requested_isos: process_country(iso=iso, dta_dir=args.dta_dir, macc_dir=args.macc_dir)

if __name__ == "__main__":
	base_dir = Path(__file__).resolve().parent.parent  # Busch2024/
	db_dir   = base_dir / "Output" / "Databases"
	dta_dir  = base_dir / "Input"
	requested_isos = iter_smallest_input_isos(dta_dir, len(list(dta_dir.glob("*.dta"))))
	print(f"Creating a fresh database; processing {len(requested_isos)} countries smallest to largest.", flush=True)
	initialize_smdamage_database(db_dir)
	for iso in requested_isos:
		size_mb = next((c.stat().st_size / 1e6 for c in [dta_dir / iso, dta_dir / f"{iso}.dta", dta_dir / f"maps_{iso}.dta"] if c.is_file()), 0)
		t0 = time.perf_counter()
		process_country(iso=iso, dta_dir=dta_dir, macc_dir=db_dir)
		elapsed = time.perf_counter() - t0
		print(f"  {elapsed:.1f}s / {size_mb:.1f} MB = {elapsed/size_mb:.2f} s/MB", flush=True)
